class CategoryItem {
  final String emoji;
  final String titleEn;
  final String titleMy;
  final List<Map<String, String>> words;
  

  CategoryItem({required this.emoji,required this.titleEn, required this.titleMy, required this.words});
}

final List<CategoryItem> appCategories = [
  CategoryItem(
    emoji: "🦝🐼",
    titleEn: "Animals",
    titleMy: "တိရစ္ဆာန်များ",
    words: [
      {"chinese": "猫", "pinyin": "māo", "english": "Cat", "myanmar": "ကြောင်"},
    {"chinese": "狗", "pinyin": "gǒu", "english": "Dog", "myanmar": "ခွေး"},
    {"chinese": "兔子", "pinyin": "tùzi", "english": "Rabbit", "myanmar": "ယုန်"},
    {"chinese": "老鼠", "pinyin": "lǎoshǔ", "english": "Mouse", "myanmar": "ကြွက်"},
    {"chinese": "牛", "pinyin": "niú", "english": "Cow", "myanmar": "နွား"},
    {"chinese": "马", "pinyin": "mǎ", "english": "Horse", "myanmar": "မြင်း"},
    {"chinese": "羊", "pinyin": "yáng", "english": "Sheep", "myanmar": "သိုး/ဆိတ်"},
    {"chinese": "猪", "pinyin": "zhū", "english": "Pig", "myanmar": "ဝက်"},
    {"chinese": "鸡", "pinyin": "jī", "english": "Chicken", "myanmar": "ကြက်"},
    {"chinese": "鸭", "pinyin": "yā", "english": "Duck", "myanmar": "ဘဲ"},
    {"chinese": "鹅", "pinyin": "é", "english": "Goose", "myanmar": "ငန်း"},
    {"chinese": "鸟", "pinyin": "niǎo", "english": "Bird", "myanmar": "ငှက်"},
    {"chinese": "鱼", "pinyin": "yú", "english": "Fish", "myanmar": "ငါး"},
    {"chinese": "虾", "pinyin": "xiā", "english": "Shrimp", "myanmar": "ပုစွန်"},
    {"chinese": "螃蟹", "pinyin": "pángxiè", "english": "Crab", "myanmar": "ဂဏန်း"},
    {"chinese": "乌龟", "pinyin": "wūguī", "english": "Turtle", "myanmar": "လိပ်"},
    {"chinese": "蛇", "pinyin": "shé", "english": "Snake", "myanmar": "မြွေ"},
    {"chinese": "青蛙", "pinyin": "qīngwā", "english": "Frog", "myanmar": "ဖား"},
    {"chinese": "猴子", "pinyin": "hóuzi", "english": "Monkey", "myanmar": "မျောက်"},
    {"chinese": "大象", "pinyin": "dàxiàng", "english": "Elephant", "myanmar": "ဆင်"},
    {"chinese": "狮子", "pinyin": "shīzi", "english": "Lion", "myanmar": "ခြင်္သေ့"},
    {"chinese": "老虎", "pinyin": "lǎohǔ", "english": "Tiger", "myanmar": "ကျား"},
    {"chinese": "熊", "pinyin": "xióng", "english": "Bear", "myanmar": "ဝက်ဝံ"},
    {"chinese": "熊猫", "pinyin": "xióngmāo", "english": "Panda", "myanmar": "ပန်ဒါ"},
    {"chinese": "狼", "pinyin": "láng", "english": "Wolf", "myanmar": "ဝံပုလွေ"},
    {"chinese": "狐狸", "pinyin": "húli", "english": "Fox", "myanmar": "မြေခွေး"},
    {"chinese": "鹿", "pinyin": "lù", "english": "Deer", "myanmar": "သမင်"},
    {"chinese": "长颈鹿", "pinyin": "chángjǐnglù", "english": "Giraffe", "myanmar": "သစ်ကုလားအုပ်"},
    {"chinese": "斑马", "pinyin": "bānmǎ", "english": "Zebra", "myanmar": "မြင်းကျား"},
    {"chinese": "河马", "pinyin": "hémǎ", "english": "Hippopotamus", "myanmar": "ရေမြင်း"},
    {"chinese": "犀牛", "pinyin": "xīniú", "english": "Rhinoceros", "myanmar": "ကြံ့"},
    {"chinese": "袋鼠", "pinyin": "dàishǔ", "english": "Kangaroo", "myanmar": "ကန်ဂရူး"},
    {"chinese": "考拉", "pinyin": "kǎolā", "english": "Koala", "myanmar": "ကိုအာလာ"},
    {"chinese": "企鹅", "pinyin": "qǐ'é", "english": "Penguin", "myanmar": "ပင်ဂွင်း"},
    {"chinese": "海豚", "pinyin": "hǎitún", "english": "Dolphin", "myanmar": "လင်းပိုင်"},
    {"chinese": "鲸鱼", "pinyin": "jīngyú", "english": "Whale", "myanmar": "ဝေလငါး"},
    {"chinese": "鲨鱼", "pinyin": "shāyú", "english": "Shark", "myanmar": "ငါးမန်း"},
    {"chinese": "章鱼", "pinyin": "zhāngyú", "english": "Octopus", "myanmar": "ရေဘဝဲ"},
    {"chinese": "海豹", "pinyin": "hǎibào", "english": "Seal", "myanmar": "ပင်လယ်ဖျံ"},
    {"chinese": "海狮", "pinyin": "hǎishī", "english": "Sea Lion", "myanmar": "ပင်လယ်ခြင်္သေ့"},
    {"chinese": "蝴蝶", "pinyin": "húdié", "english": "Butterfly", "myanmar": "လိပ်ပြာ"},
    {"chinese": "蜜蜂", "pinyin": "mìfēng", "english": "Bee", "myanmar": "ပျား"},
    {"chinese": "蚂蚁", "pinyin": "mǎyǐ", "english": "Ant", "myanmar": "ပုရွက်ဆိတ်"},
    {"chinese": "蜘蛛", "pinyin": "zhīzhū", "english": "Spider", "myanmar": "ပင်ကူ"},
    {"chinese": "蚊子", "pinyin": "wénzi", "english": "Mosquito", "myanmar": "ခြင်"},
    {"chinese": "苍蝇", "pinyin": "cāngying", "english": "Fly", "myanmar": "ယင်ကောင်"},
    {"chinese": "蜻蜓", "pinyin": "qīngtíng", "english": "Dragonfly", "myanmar": "ပုစဥ်း"},
    {"chinese": "蚯蚓", "pinyin": "qiūyǐn", "english": "Earthworm", "myanmar": "တီကောင်"},
    {"chinese": "蜗牛", "pinyin": "wōniú", "english": "Snail", "myanmar": "ခရု"},
    {"chinese": "蚕", "pinyin": "cán", "english": "Silkworm", "myanmar": "ပိုးတီ"},
    {"chinese": "蟑螂", "pinyin": "zhāngláng", "english": "Cockroach", "myanmar": "ပိုးဟပ်"},
    {"chinese": "甲虫", "pinyin": "jiǎchóng", "english": "Beetle", "myanmar": "ကျိုင်းကောင်"},
    {"chinese": "瓢虫", "pinyin": "piáochóng", "english": "Ladybug", "myanmar": "ပိုးတောင်မာ"},
    {"chinese": "螳螂", "pinyin": "tángláng", "english": "Mantis", "myanmar": "လက်ဝှေ့ကောင်"},
    {"chinese": "蝗虫", "pinyin": "huángchóng", "english": "Locust", "myanmar": "နှံကောင်"},
    {"chinese": "蟋蟀", "pinyin": "xīshuài", "english": "Cricket", "myanmar": "ပိုးဟုန်း"},
    {"chinese": "蝉", "pinyin": "chán", "english": "Cicada", "myanmar": "ပုစဥ်းရင်ကွဲ"},
    {"chinese": "鳄鱼", "pinyin": "èyú", "english": "Crocodile", "myanmar": "မိကျောင်း"},
    {"chinese": "长臂猿", "pinyin": "chángbìyuán", "english": "Gibbon", "myanmar": "လက်ရှည်မျောက်"},
    {"chinese": "猩猩", "pinyin": "xīngxing", "english": "Orangutan", "myanmar": "လူဝံ"},
    {"chinese": "大猩猩", "pinyin": "dàxīngxing", "english": "Gorilla", "myanmar": "ဂိုရီလာ"},
    {"chinese": "骆驼", "pinyin": "luòtuo", "english": "Camel", "myanmar": "ကုလားအုပ်"},
    {"chinese": "驴", "pinyin": "lǘ", "english": "Donkey", "myanmar": "မြည်း"},
    {"chinese": "骡", "pinyin": "luó", "english": "Mule", "myanmar": "လား"},
    {"chinese": "山羊", "pinyin": "shānyáng", "english": "Goat", "myanmar": "ဆိတ်"},
    {"chinese": "水牛", "pinyin": "shuǐniú", "english": "Buffalo", "myanmar": "ကျွဲ"},
    {"chinese": "牦牛", "pinyin": "máoniú", "english": "Yak", "myanmar": "စာမရီ"},
    {"chinese": "松鼠", "pinyin": "sōngshǔ", "english": "Squirrel", "myanmar": "ရှဥ့်"},
    {"chinese": "刺猬", "pinyin": "cìwei", "english": "Hedgehog", "myanmar": "ဖြူ"},
    {"chinese": "浣熊", "pinyin": "huǎnxióng", "english": "Raccoon", "myanmar": "ရက်ကွန်း"},
    {"chinese": "野猪", "pinyin": "yězhū", "english": "Wild Boar", "myanmar": "တောဝက်"},
    {"chinese": "梅花鹿", "pinyin": "méihuālù", "english": "Sika Deer", "myanmar": "ဒရယ်"},
    {"chinese": "麋鹿", "pinyin": "mílù", "english": "Père David's Deer", "myanmar": "မြီးလုသမင်"},
    {"chinese": "羚羊", "pinyin": "língyáng", "english": "Antelope", "myanmar": "ကျွေသမင်"},
    {"chinese": "羚牛", "pinyin": "língniú", "english": "Takin", "myanmar": "တာကင်းဆိတ်နွား"},
    {"chinese": "野兔", "pinyin": "yětù", "english": "Hare", "myanmar": "တောယုန်"},
    {"chinese": "鼹鼠", "pinyin": "yǎnshǔ", "english": "Mole", "myanmar": "မြေကြွက်"},
    {"chinese": "蝙蝠", "pinyin": "biānfú", "english": "Bat", "myanmar": "လင်းနို့"},
    {"chinese": "袋熊", "pinyin": "dàixióng", "english": "Wombat", "myanmar": "ဝမ်ဘတ်"},
    {"chinese": "树懒", "pinyin": "shùlǎn", "english": "Sloth", "myanmar": "ဆလော့"},
    {"chinese": "食蚁兽", "pinyin": "shíyǐshòu", "english": "Anteater", "myanmar": "ပုရွက်ဆိတ်စားကောင်"},
    {"chinese": "穿山甲", "pinyin": "chuānshānjiǎ", "english": "Pangolin", "myanmar": "သင်းခွေချပ်"},
    {"chinese": "孔雀", "pinyin": "kǒngquè", "english": "Peacock", "myanmar": "ဥဒေါင်း"},
    {"chinese": "鸵鸟", "pinyin": "tuóniǎo", "english": "Ostrich", "myanmar": "ငှက်ကုလားအုပ်"},
    {"chinese": "火烈鸟", "pinyin": "huǒlièniǎo", "english": "Flamingo", "myanmar": "ဖလမင်းဂို"},
    {"chinese": "鹦鹉", "pinyin": "yīngwǔ", "english": "Parrot", "myanmar": "ကြက်တူရွေး"},
    {"chinese": "鸽子", "pinyin": "gēzi", "english": "Pigeon", "myanmar": "ခို"},
    {"chinese": "乌鸦", "pinyin": "wūyā", "english": "Crow", "myanmar": "ကျီးကန်း"},
    {"chinese": "麻雀", "pinyin": "máquè", "english": "Sparrow", "myanmar": "စာကလေး"},
    {"chinese": "啄木鸟", "pinyin": "zhuómùniǎo", "english": "Woodpecker", "myanmar": "သစ်တောက်ငှက်"},
    {"chinese": "猫头鹰", "pinyin": "māotóuyīng", "english": "Owl", "myanmar": "ဇီးကွက်"},
    {"chinese": "天鹅", "pinyin": "tiān'é", "english": "Swan", "myanmar": "ငန်းဖြူ"},
    {"chinese": "鹤", "pinyin": "hè", "english": "Crane", "myanmar": "ကြိုးကြာငှက်"},
    {"chinese": "鹰", "pinyin": "yīng", "english": "Eagle", "myanmar": "လင်းယုန်"},
    {"chinese": "猎豹", "pinyin": "lièbào", "english": "Cheetah", "myanmar": "ချီတာကျားသစ်"},
    {"chinese": "变色龙", "pinyin": "biànsèlóng", "english": "Chameleon", "myanmar": "ပုတ်သင်ညို"},
    {"chinese": "水母", "pinyin": "shuǐmǔ", "english": "Jellyfish", "myanmar": "ရေဂျယ်လီ"},
    {"chinese": "海龟", "pinyin": "hǎiguī", "english": "Sea Turtle", "myanmar": "ပင်လယ်လိပ်"},
    {"chinese": "水獭", "pinyin": "shuǐtǎ", "english": "Otter", "myanmar": "ဖျံ"},
    {"chinese": "海马", "pinyin": "hǎimǎ", "english": "Seahorse", "myanmar": "ပင်လယ်မြင်း"},
    ],
  ),
  CategoryItem(
    emoji: "🎊",
    titleEn: "Colours",
    titleMy: "အရောင်များ",
    words: [
      {"chinese": "红色", "pinyin": "hóngsè", "english": "Red", "myanmar": "အနီရောင်"},
    {"chinese": "橙色", "pinyin": "chéngsè", "english": "Orange", "myanmar": "လိမ္မော်ရောင်"},
    {"chinese": "黄色", "pinyin": "huángsè", "english": "Yellow", "myanmar": "အဝါရောင်"},
    {"chinese": "绿色", "pinyin": "lǜsè", "english": "Green", "myanmar": "အစိမ်းရောင်"},
    {"chinese": "蓝色", "pinyin": "lánsè", "english": "Blue", "myanmar": "အပြာရောင်"},
    {"chinese": "紫色", "pinyin": "zǐsè", "english": "Purple", "myanmar": "ခရမ်းရောင်"},
    {"chinese": "黑色", "pinyin": "hēisè", "english": "Black", "myanmar": "အနက်ရောင်"},
    {"chinese": "白色", "pinyin": "báisè", "english": "White", "myanmar": "အဖြူရောင်"},
    {"chinese": "灰色", "pinyin": "huīsè", "english": "Grey", "myanmar": "မီးခိုးရောင်"},
    {"chinese": "粉色", "pinyin": "fěnsè", "english": "Pink", "myanmar": "ပန်းရောင်"},
    {"chinese": "棕色", "pinyin": "zōngsè", "english": "Brown", "myanmar": "အညိုရောင်"},
    {"chinese": "金色", "pinyin": "jīnsè", "english": "Gold", "myanmar": "ရွှေရောင်"},
    {"chinese": "银色", "pinyin": "yínsè", "english": "Silver", "myanmar": "ငွေရောင်"},
    {"chinese": "米色", "pinyin": "mǐsè", "english": "Beige", "myanmar": "အသားရောင်"},
    {"chinese": "青色", "pinyin": "qīngsè", "english": "Cyan", "myanmar": "အပြာစိမ်းရောင်"},
    {"chinese": "蓝绿色", "pinyin": "lánlǜsè", "english": "Teal", "myanmar": "အပြာစိမ်း"},
    {"chinese": "深红色", "pinyin": "shēnhóngsè", "english": "Dark Red", "myanmar": "အနီရင့်"},
    {"chinese": "浅红色", "pinyin": "qiǎnhóngsè", "english": "Light Red", "myanmar": "အနီနု"},
    {"chinese": "深橙色", "pinyin": "shēnchéngsè", "english": "Dark Orange", "myanmar": "လိမ္မော်ရင့်"},
    {"chinese": "浅橙色", "pinyin": "qiǎnchéngsè", "english": "Light Orange", "myanmar": "လိမ္မော်နု"},
    {"chinese": "深黄色", "pinyin": "shēnhuángsè", "english": "Dark Yellow", "myanmar": "အဝါရင့်"},
    {"chinese": "浅黄色", "pinyin": "qiǎnhuángsè", "english": "Light Yellow", "myanmar": "အဝါနု"},
    {"chinese": "深绿色", "pinyin": "shēnlǜsè", "english": "Dark Green", "myanmar": "အစိမ်းရင့်"},
    {"chinese": "浅绿色", "pinyin": "qiǎnlǜsè", "english": "Light Green", "myanmar": "အစိမ်းနု"},
    {"chinese": "深蓝色", "pinyin": "shēnlánsè", "english": "Dark Blue", "myanmar": "အပြာရင့်"},
    {"chinese": "浅蓝色", "pinyin": "qiǎnlánsè", "english": "Light Blue", "myanmar": "အပြာနု"},
    {"chinese": "深紫色", "pinyin": "shēnzǐsè", "english": "Dark Purple", "myanmar": "ခရမ်းရင့်"},
    {"chinese": "浅紫色", "pinyin": "qiǎnzǐsè", "english": "Light Purple", "myanmar": "ခရမ်းနု"},
    {"chinese": "深灰色", "pinyin": "shēnhuīsè", "english": "Dark Grey", "myanmar": "မီးခိုးရင့်"},
    {"chinese": "浅灰色", "pinyin": "qiǎnhuīsè", "english": "Light Grey", "myanmar": "မီးခိုးနု"},
    {"chinese": "深棕色", "pinyin": "shēnzōngsè", "english": "Dark Brown", "myanmar": "အညိုရင့်"},
    {"chinese": "浅棕色", "pinyin": "qiǎnzōngsè", "english": "Light Brown", "myanmar": "အညိုနု"},
    {"chinese": "玫红色", "pinyin": "méihóngsè", "english": "Rose Red", "myanmar": "နှင်းဆီနီ"},
    {"chinese": "桃红色", "pinyin": "táohóngsè", "english": "Peach Red", "myanmar": "မက်မွန်နီ"},
    {"chinese": "粉红色", "pinyin": "fěnhóngsè", "english": "Pink", "myanmar": "ပန်းရောင်"},
    {"chinese": "珊瑚色", "pinyin": "shānhúsè", "english": "Coral", "myanmar": "သန္တာရောင်"},
    {"chinese": "杏色", "pinyin": "xìngsè", "english": "Apricot", "myanmar": "အက်ပရီကော့ရောင်"},
    {"chinese": "奶油色", "pinyin": "nǎiyóusè", "english": "Cream", "myanmar": "နို့ဆီရောင်"},
    {"chinese": "象牙色", "pinyin": "xiàngyásè", "english": "Ivory", "myanmar": "ဆင်စွယ်ရောင်"},
    {"chinese": "香槟色", "pinyin": "xiāngbīnsè", "english": "Champagne", "myanmar": "ရှန်ပိန်ရောင်"},
    {"chinese": "卡其色", "pinyin": "kǎqísè", "english": "Khaki", "myanmar": "ခါကီရောင်"},
    {"chinese": "咖啡色", "pinyin": "kāfēisè", "english": "Coffee Brown", "myanmar": "ကော်ဖီရောင်"},
    {"chinese": "栗色", "pinyin": "lìsè", "english": "Chestnut", "myanmar": "သစ်အယ်သီးညို"},
    {"chinese": "酒红色", "pinyin": "jiǔhóngsè", "english": "Wine Red", "myanmar": "ဝိုင်နီရောင်"},
    {"chinese": "砖红色", "pinyin": "zhuānhóngsè", "english": "Brick Red", "myanmar": "အုတ်နီရောင်"},
    {"chinese": "朱红色", "pinyin": "zhūhóngsè", "english": "Vermilion", "myanmar": "ဟင်္သပြားနီ"},
    {"chinese": "橘红色", "pinyin": "júhóngsè", "english": "Tangerine Red", "myanmar": "လိမ္မော်နီ"},
    {"chinese": "橘黄色", "pinyin": "júhuángsè", "english": "Tangerine Yellow", "myanmar": "လိမ္မော်ဝါ"},
    {"chinese": "柠檬黄", "pinyin": "níngménghuáng", "english": "Lemon Yellow", "myanmar": "သံပရာဝါ"},
    {"chinese": "柠檬绿", "pinyin": "níngménglǜ", "english": "Lime Green", "myanmar": "သံပရာစိမ်း"},
    {"chinese": "草绿色", "pinyin": "cǎolǜsè", "english": "Grass Green", "myanmar": "မြက်ခင်းစိမ်း"},
    {"chinese": "森林绿", "pinyin": "sēnlínlǜ", "english": "Forest Green", "myanmar": "သစ်တောစိမ်း"},
    {"chinese": "橄榄绿", "pinyin": "gǎnlǎnlǜ", "english": "Olive Green", "myanmar": "သံလွင်စိမ်း"},
    {"chinese": "薄荷绿", "pinyin": "bòhelǜ", "english": "Mint Green", "myanmar": "ပူစီနံစိမ်း"},
    {"chinese": "青绿色", "pinyin": "qīnglǜsè", "english": "Turquoise Green", "myanmar": "အပြာစိမ်း"},
    {"chinese": "翡翠绿", "pinyin": "fěicuìlǜ", "english": "Emerald Green", "myanmar": "မြရောင်အစိမ်း"},
    {"chinese": "松绿色", "pinyin": "sōnglǜsè", "english": "Pine Green", "myanmar": "ထင်းရှူးစိမ်း"},
    {"chinese": "湖蓝色", "pinyin": "húlánsè", "english": "Lake Blue", "myanmar": "ကန်ပြာရောင်"},
    {"chinese": "天蓝色", "pinyin": "tiānlánsè", "english": "Sky Blue", "myanmar": "ကောင်းကင်ပြာ"},
    {"chinese": "宝蓝色", "pinyin": "bǎolánsè", "english": "Royal Blue", "myanmar": "ရော်ယယ်ပြာ"},
    {"chinese": "藏青色", "pinyin": "zàngqīngsè", "english": "Navy Blue", "myanmar": "ရေတပ်ပြာ"},
    {"chinese": "海蓝色", "pinyin": "hǎilánsè", "english": "Ocean Blue", "myanmar": "ပင်လယ်ပြာ"},
    {"chinese": "靛蓝色", "pinyin": "diànlánsè", "english": "Indigo", "myanmar": "မဲနယ်ပြာ"},
    {"chinese": "紫罗兰色", "pinyin": "zǐluólánsè", "english": "Violet", "myanmar": "ဗိုင်းအိုလက်"},
    {"chinese": "薰衣草色", "pinyin": "xūnyīcǎosè", "english": "Lavender", "myanmar": "လာဗင်ဒါ"},
    {"chinese": "葡萄紫", "pinyin": "pútáozǐ", "english": "Grape Purple", "myanmar": "စပျစ်ခရမ်း"},
    {"chinese": "梅紫色", "pinyin": "méizǐsè", "english": "Plum Purple", "myanmar": "ဇီးခရမ်း"},
    {"chinese": "玫瑰色", "pinyin": "méiguīsè", "english": "Rose", "myanmar": "နှင်းဆီရောင်"},
    {"chinese": "樱桃红", "pinyin": "yīngtáohóng", "english": "Cherry Red", "myanmar": "ချယ်ရီနီ"},
    {"chinese": "樱花粉", "pinyin": "yīnghuāfěn", "english": "Cherry Blossom Pink", "myanmar": "ချယ်ရီပန်းရောင်"},
    {"chinese": "珊瑚红", "pinyin": "shānhúhóng", "english": "Coral Red", "myanmar": "သန္တာနီ"},
    {"chinese": "砖黄色", "pinyin": "zhuānhuángsè", "english": "Brick Yellow", "myanmar": "အုတ်ဝါရောင်"},
    {"chinese": "土黄色", "pinyin": "tǔhuángsè", "english": "Earthy Yellow", "myanmar": "မြေဝါရောင်"},
    {"chinese": "金黄色", "pinyin": "jīnhuángsè", "english": "Golden Yellow", "myanmar": "ရွှေဝါရောင်"},
    {"chinese": "银灰色", "pinyin": "yínhuīsè", "english": "Silver Grey", "myanmar": "ငွေမီးခိုး"},
    {"chinese": "烟灰色", "pinyin": "yānhuīsè", "english": "Smoky Grey", "myanmar": "မီးခိုးမှောင်"},
    {"chinese": "炭黑色", "pinyin": "tànhēisè", "english": "Charcoal Black", "myanmar": "မီးသွေးနက်"},
    {"chinese": "象牙白", "pinyin": "xiàngyábái", "english": "Ivory White", "myanmar": "ဆင်စွယ်ဖြူ"},
    {"chinese": "乳白色", "pinyin": "rǔbáisè", "english": "Milky White", "myanmar": "နို့ဖြူရောင်"},
    {"chinese": "纯白色", "pinyin": "chúnbáisè", "english": "Pure White", "myanmar": "အဖြူထည်"},
    {"chinese": "纯黑色", "pinyin": "chúnhēisè", "english": "Pure Black", "myanmar": "အနက်ထည်"},
    {"chinese": "亮红色", "pinyin": "liànghóngsè", "english": "Bright Red", "myanmar": "အနီတောက်ပ"},
    {"chinese": "亮黄色", "pinyin": "liànghuángsè", "english": "Bright Yellow", "myanmar": "အဝါတောက်ပ"},
    {"chinese": "亮绿色", "pinyin": "liànglǜsè", "english": "Bright Green", "myanmar": "အစိမ်းတောက်ပ"},
    {"chinese": "亮蓝色", "pinyin": "liànglánsè", "english": "Bright Blue", "myanmar": "အပြာတောက်ပ"},
    {"chinese": "亮紫色", "pinyin": "liàngzǐsè", "english": "Bright Purple", "myanmar": "ခရမ်းတောက်ပ"},
    {"chinese": "暗红色", "pinyin": "ànhóngsè", "english": "Dark Red", "myanmar": "အနီမှောင်"},
    {"chinese": "暗黄色", "pinyin": "ànhuángsè", "english": "Dark Yellow", "myanmar": "အဝါမှောင်"},
    {"chinese": "暗绿色", "pinyin": "ànlǜsè", "english": "Dark Green", "myanmar": "အစိမ်းမှောင်"},
    {"chinese": "暗蓝色", "pinyin": "ànlánsè", "english": "Dark Blue", "myanmar": "အပြာမှောင်"},
    {"chinese": "暗紫色", "pinyin": "ànzǐsè", "english": "Dark Purple", "myanmar": "ခရမ်းမှောင်"},
    {"chinese": "透明色", "pinyin": "tòumíngsè", "english": "Transparent", "myanmar": "ကြည်လင်သော"},
    {"chinese": "彩色", "pinyin": "cǎisè", "english": "Colorful", "myanmar": "အရောင်စုံ"},
    {"chinese": "无色", "pinyin": "wúsè", "english": "Colorless", "myanmar": "အရောင်မရှိသော"},
    {"chinese": "多色", "pinyin": "duōsè", "english": "Multicolor", "myanmar": "အရောင်အများအပြား"},
    {"chinese": "琥珀色", "pinyin": "hǔpòsè", "english": "Amber", "myanmar": "ပယင်းရောင်"},
    {"chinese": "玫瑰金", "pinyin": "méiguījīn", "english": "Rose Gold", "myanmar": "နှင်းဆီရွှေရောင်"},
    {"chinese": "古铜色", "pinyin": "gǔtóngsè", "english": "Bronze", "myanmar": "ကြေးညိုရောင်"},
    {"chinese": "荧光绿", "pinyin": "yíngguānglǜ", "english": "Fluorescent Green", "myanmar": "မီးချောင်းစိမ်း"},
    {"chinese": "墨绿色", "pinyin": "mòlǜsè", "english": "Dark Green", "myanmar": "မင်စိမ်းရောင်"},
    ],
  ),
  CategoryItem(
    emoji: "🔢",
    titleEn: "Numbers",
    titleMy: "ဂဏန်းများ",
    words: [
      {"chinese": "零", "pinyin": "líng", "english": "Zero", "myanmar": "သုည"},
    {"chinese": "一", "pinyin": "yī", "english": "One", "myanmar": "တစ်"},
    {"chinese": "二", "pinyin": "èr", "english": "Two", "myanmar": "နှစ်"},
    {"chinese": "三", "pinyin": "sān", "english": "Three", "myanmar": "သုံး"},
    {"chinese": "四", "pinyin": "sì", "english": "Four", "myanmar": "လေး"},
    {"chinese": "五", "pinyin": "wǔ", "english": "Five", "myanmar": "ငါး"},
    {"chinese": "六", "pinyin": "liù", "english": "Six", "myanmar": "ခြောက်"},
    {"chinese": "七", "pinyin": "qī", "english": "Seven", "myanmar": "ခုနစ်"},
    {"chinese": "八", "pinyin": "bā", "english": "Eight", "myanmar": "ရှစ်"},
    {"chinese": "九", "pinyin": "jiǔ", "english": "Nine", "myanmar": "ကိုး"},
    {"chinese": "十", "pinyin": "shí", "english": "Ten", "myanmar": "ဆယ်"},
    {"chinese": "十一", "pinyin": "shíyī", "english": "Eleven", "myanmar": "တစ်ဆယ့်တစ်"},
    {"chinese": "十二", "pinyin": "shí'èr", "english": "Twelve", "myanmar": "တစ်ဆယ့်နှစ်"},
    {"chinese": "十三", "pinyin": "shísān", "english": "Thirteen", "myanmar": "တစ်ဆယ့်သုံး"},
    {"chinese": "十四", "pinyin": "shísì", "english": "Fourteen", "myanmar": "တစ်ဆယ့်လေး"},
    {"chinese": "十五", "pinyin": "shíwǔ", "english": "Fifteen", "myanmar": "တစ်ဆယ့်ငါး"},
    {"chinese": "十六", "pinyin": "shíliù", "english": "Sixteen", "myanmar": "တစ်ဆယ့်ခြောက်"},
    {"chinese": "十七", "pinyin": "shíqī", "english": "Seventeen", "myanmar": "တစ်ဆယ့်ခုနစ်"},
    {"chinese": "十八", "pinyin": "shíbā", "english": "Eighteen", "myanmar": "တစ်ဆယ့်ရှစ်"},
    {"chinese": "十九", "pinyin": "shíjiǔ", "english": "Nineteen", "myanmar": "တစ်ဆယ့်ကိုး"},
    {"chinese": "二十", "pinyin": "èrshí", "english": "Twenty", "myanmar": "နှစ်ဆယ်"},
    {"chinese": "二十一", "pinyin": "èrshíyī", "english": "Twenty-one", "myanmar": "နှစ်ဆယ့်တစ်"},
    {"chinese": "二十二", "pinyin": "èrshí'èr", "english": "Twenty-two", "myanmar": "နှစ်ဆယ့်နှစ်"},
    {"chinese": "二十三", "pinyin": "èrshísān", "english": "Twenty-three", "myanmar": "နှစ်ဆယ့်သုံး"},
    {"chinese": "二十四", "pinyin": "èrshísì", "english": "Twenty-four", "myanmar": "နှစ်ဆယ့်လေး"},
    {"chinese": "二十五", "pinyin": "èrshíwǔ", "english": "Twenty-five", "myanmar": "နှစ်ဆယ့်ငါး"},
    {"chinese": "二十六", "pinyin": "èrshíliù", "english": "Twenty-six", "myanmar": "နှစ်ဆယ့်ခြောက်"},
    {"chinese": "二十七", "pinyin": "èrshíqī", "english": "Twenty-seven", "myanmar": "နှစ်ဆယ့်ခုနစ်"},
    {"chinese": "二十八", "pinyin": "èrshíbā", "english": "Twenty-eight", "myanmar": "နှစ်ဆယ့်ရှစ်"},
    {"chinese": "二十九", "pinyin": "èrshíjiǔ", "english": "Twenty-nine", "myanmar": "နှစ်ဆယ့်ကိုး"},
    {"chinese": "三十", "pinyin": "sānshí", "english": "Thirty", "myanmar": "သုံးဆယ်"},
    {"chinese": "四十", "pinyin": "sìshí", "english": "Forty", "myanmar": "လေးဆယ်"},
    {"chinese": "五十", "pinyin": "wǔshí", "english": "Fifty", "myanmar": "ငါးဆယ်"},
    {"chinese": "六十", "pinyin": "liùshí", "english": "Sixty", "myanmar": "ခြောက်ဆယ်"},
    {"chinese": "七十", "pinyin": "qīshí", "english": "Seventy", "myanmar": "ခုနစ်ဆယ်"},
    {"chinese": "八十", "pinyin": "bāshí", "english": "Eighty", "myanmar": "ရှစ်ဆယ်"},
    {"chinese": "九十", "pinyin": "jiǔshí", "english": "Ninety", "myanmar": "ကိုးဆယ်"},
    {"chinese": "一百", "pinyin": "yìbǎi", "english": "One hundred", "myanmar": "တစ်ရာ"},
    {"chinese": "一千", "pinyin": "yìqiān", "english": "One thousand", "myanmar": "တစ်ထောင်"},
    {"chinese": "一万", "pinyin": "yíwàn", "english": "Ten thousand", "myanmar": "တစ်သောင်း"},
    {"chinese": "十万", "pinyin": "shíwàn", "english": "One hundred thousand", "myanmar": "တစ်သိန်း"},
    {"chinese": "一百万", "pinyin": "yìbǎiwàn", "english": "One million", "myanmar": "တစ်သန်း"},
    {"chinese": "一千万", "pinyin": "yìqiānwàn", "english": "Ten million", "myanmar": "ဆယ်သန်း"},
    {"chinese": "一亿", "pinyin": "yíyì", "english": "One hundred million", "myanmar": "သန်း ၁၀၀"},
    {"chinese": "第一", "pinyin": "dì-yī", "english": "First", "myanmar": "ပထမ"},
    {"chinese": "第二", "pinyin": "dì-'èr", "english": "Second", "myanmar": "ဒုတိယ"},
    {"chinese": "第三", "pinyin": "dì-sān", "english": "Third", "myanmar": "တတိယ"},
    {"chinese": "第四", "pinyin": "dì-sì", "english": "Fourth", "myanmar": "စတုတ္ထ"},
    {"chinese": "第五", "pinyin": "dì-wǔ", "english": "Fifth", "myanmar": "ပဉ္စမ"},
    {"chinese": "第六", "pinyin": "dì-liù", "english": "Sixth", "myanmar": "ဆဋ္ဌမ"},
    {"chinese": "第七", "pinyin": "dì-qī", "english": "Seventh", "myanmar": "သတ္တမ"},
    {"chinese": "第八", "pinyin": "dì-bā", "english": "Eighth", "myanmar": "အဋ္ဌမ"},
    {"chinese": "第九", "pinyin": "dì-jiǔ", "english": "Ninth", "myanmar": "နဝမ"},
    {"chinese": "第十", "pinyin": "dì-shí", "english": "Tenth", "myanmar": "ဒသမ"},
    {"chinese": "两", "pinyin": "liǎng", "english": "Two", "myanmar": "နှစ် (ခု)"},
    {"chinese": "双", "pinyin": "shuāng", "english": "Pair", "myanmar": "အစုံ"},
    {"chinese": "单", "pinyin": "dān", "english": "Single", "myanmar": "တစ်လုံးတည်း/မကိန်း"},
    {"chinese": "半", "pinyin": "bàn", "english": "Half", "myanmar": "တစ်ဝက်"},
    {"chinese": "一半", "pinyin": "yíbàn", "english": "Half", "myanmar": "တစ်ဝက်"},
    {"chinese": "一倍", "pinyin": "yíbèi", "english": "Onefold / 1x", "myanmar": "တစ်ဆ"},
    {"chinese": "两倍", "pinyin": "liǎngbèi", "english": "Double / 2x", "myanmar": "နှစ်ဆ"},
    {"chinese": "三倍", "pinyin": "sānbèi", "english": "Triple / 3x", "myanmar": "သုံးဆ"},
    {"chinese": "四倍", "pinyin": "sìbèi", "english": "Fourfold", "myanmar": "လေးဆ"},
    {"chinese": "五倍", "pinyin": "wǔbèi", "english": "Fivefold", "myanmar": "ငါးဆ"},
    {"chinese": "几", "pinyin": "jǐ", "english": "How many / Several", "myanmar": "ဘယ်လောက်/အနည်းငယ်"},
    {"chinese": "几个", "pinyin": "jǐ gè", "english": "A few / Several", "myanmar": "အနည်းငယ်"},
    {"chinese": "一些", "pinyin": "yìxiē", "english": "Some", "myanmar": "အချို့"},
    {"chinese": "一点", "pinyin": "yìdiǎn", "english": "A little", "myanmar": "နည်းနည်း"},
    {"chinese": "一点儿", "pinyin": "yìdiǎnr", "english": "A little bit", "myanmar": "နည်းနည်းပါးပါး"},
    {"chinese": "很多", "pinyin": "hěnduō", "english": "A lot / Many", "myanmar": "အများကြီး"},
    {"chinese": "少数", "pinyin": "shǎoshù", "english": "Minority", "myanmar": "အနည်းစု"},
    {"chinese": "多数", "pinyin": "duōshù", "english": "Majority", "myanmar": "အများစု"},
    {"chinese": "全部", "pinyin": "quánbù", "english": "All / Whole", "myanmar": "အားလုံး"},
    {"chinese": "一共", "pinyin": "yígòng", "english": "Altogether", "myanmar": "စုစုပေါင်း"},
    {"chinese": "总共", "pinyin": "zǒnggòng", "english": "In total", "myanmar": "စုစုပေါင်း"},
    {"chinese": "每个", "pinyin": "měi gè", "english": "Each / Every", "myanmar": "တစ်ခုစီ/တိုင်း"},
    {"chinese": "每次", "pinyin": "měi cì", "english": "Every time", "myanmar": "အကြိမ်တိုင်း"},
    {"chinese": "每人", "pinyin": "měi rén", "english": "Per person / Everyone", "myanmar": "လူတိုင်း"},
    {"chinese": "每年", "pinyin": "měi nián", "english": "Every year", "myanmar": "နှစ်တိုင်း"},
    {"chinese": "每月", "pinyin": "měi yuè", "english": "Every month", "myanmar": "လတိုင်း"},
    {"chinese": "每天", "pinyin": "měi tiān", "english": "Every day", "myanmar": "ရက်တိုင်း"},
    {"chinese": "一次", "pinyin": "yí cì", "english": "Once", "myanmar": "တစ်ကြိမ်"},
    {"chinese": "两次", "pinyin": "liǎng cì", "english": "Twice", "myanmar": "နှစ်ကြိမ်"},
    {"chinese": "三次", "pinyin": "sān cì", "english": "Three times", "myanmar": "သုံးကြိမ်"},
    {"chinese": "四次", "pinyin": "sì cì", "english": "Four times", "myanmar": "လေးကြိမ်"},
    {"chinese": "五次", "pinyin": "wǔ cì", "english": "Five times", "myanmar": "ငါးကြိမ်"},
    {"chinese": "首先", "pinyin": "shǒuxiān", "english": "Firstly", "myanmar": "ပထမဦးစွာ"},
    {"chinese": "其次", "pinyin": "qícì", "english": "Secondly", "myanmar": "ဒုတိယအချက်အနေဖြင့်"},
    {"chinese": "最后", "pinyin": "zuìhòu", "english": "Finally / Last", "myanmar": "နောက်ဆုံးတွင်"},
    {"chinese": "第一名", "pinyin": "dì-yī míng", "english": "First place", "myanmar": "ပထမနေရာ/ပထမဆု"},
    {"chinese": "第二名", "pinyin": "dì-'èr míng", "english": "Second place", "myanmar": "ဒုတိယနေရာ/ဒုတိယဆု"},
    {"chinese": "第三名", "pinyin": "dì-sān míng", "english": "Third place", "myanmar": "တတိယနေရာ/တတိယဆု"},
    {"chinese": "数量", "pinyin": "shùliàng", "english": "Quantity", "myanmar": "အရေအတွက်"},
    {"chinese": "数字", "pinyin": "shùzì", "english": "Number / Digit", "myanmar": "ကိန်းဂဏန်း"},
    {"chinese": "号码", "pinyin": "hàomǎ", "english": "Number", "myanmar": "နံပါတ်"},
    {"chinese": "编号", "pinyin": "biānhào", "english": "Serial number", "myanmar": "နံပါတ်စဉ်"},
    {"chinese": "总数", "pinyin": "zǒngshù", "english": "Total count", "myanmar": "စုစုပေါင်း အရေအတွက်"},
    {"chinese": "整数", "pinyin": "zhěngshù", "english": "Integer", "myanmar": "ကိန်းပြည့်"},
    {"chinese": "小数", "pinyin": "xiǎoshù", "english": "Decimal", "myanmar": "ဒသမကိန်း"},
    {"chinese": "分数", "pinyin": "fēnshù", "english": "Fraction / Score", "myanmar": "အပိုင်းကိန်း/အမှတ်"},
    {"chinese": "百分之百", "pinyin": "bǎifēnzhībǎi", "english": "100%", "myanmar": "ရာခိုင်နှုန်းပြည့်"},
    ],
  ),
  CategoryItem(
    emoji: "🥝🥭",
    titleEn: "Fruits",
    titleMy: "သစ်သီးဝလံများ",
    words: [
      {"chinese": "苹果", "pinyin": "píngguǒ", "english": "Apple", "myanmar": "ပန်းသီး"},
    {"chinese": "香蕉", "pinyin": "xiāngjiāo", "english": "Banana", "myanmar": "ငှက်ပျောသီး"},
    {"chinese": "橙子", "pinyin": "chéngzi", "english": "Orange", "myanmar": "လိမ္မော်သီး"},
    {"chinese": "橘子", "pinyin": "júzi", "english": "Mandarin / Tangerine", "myanmar": "ကမ္ဗလာသီး / လိမ္မော်သီး"},
    {"chinese": "葡萄", "pinyin": "pútáo", "english": "Grape", "myanmar": "စပျစ်သီး"},
    {"chinese": "西瓜", "pinyin": "xīguā", "english": "Watermelon", "myanmar": "ဖရဲသီး"},
    {"chinese": "草莓", "pinyin": "cǎoméi", "english": "Strawberry", "myanmar": "စထရော်ဘယ်ရီ"},
    {"chinese": "蓝莓", "pinyin": "lánméi", "english": "Blueberry", "myanmar": "ဘလူးဘယ်ရီ"},
    {"chinese": "树莓", "pinyin": "shùméi", "english": "Raspberry", "myanmar": "ရက်စ်ဘယ်ရီ"},
    {"chinese": "樱桃", "pinyin": "yīngtáo", "english": "Cherry", "myanmar": "ချယ်ရီသီး"},
    {"chinese": "桃子", "pinyin": "táozi", "english": "Peach", "myanmar": "မက်မွန်သီး"},
    {"chinese": "梨", "pinyin": "lí", "english": "Pear", "myanmar": "သစ်တော်သီး"},
    {"chinese": "柿子", "pinyin": "shìzi", "english": "Persimmon", "myanmar": "တည်သီး"},
    {"chinese": "芒果", "pinyin": "mángguǒ", "english": "Mango", "myanmar": "သရက်သီး"},
    {"chinese": "菠萝", "pinyin": "bōluó", "english": "Pineapple", "myanmar": "နာနတ်သီး"},
    {"chinese": "木瓜", "pinyin": "mùguā", "english": "Papaya", "myanmar": "သင်္ဘောသီး"},
    {"chinese": "椰子", "pinyin": "yēzi", "english": "Coconut", "myanmar": "အုန်းသီး"},
    {"chinese": "柠檬", "pinyin": "níngméng", "english": "Lemon", "myanmar": "သံပရိုသီး"},
    {"chinese": "青柠", "pinyin": "qīngníng", "english": "Lime", "myanmar": "သံပရာသီး"},
    {"chinese": "石榴", "pinyin": "shíliú", "english": "Pomegranate", "myanmar": "သလဲသီး"},
    {"chinese": "火龙果", "pinyin": "huǒlóngguǒ", "english": "Dragonfruit", "myanmar": "နဂါးမောက်သီး"},
    {"chinese": "猕猴桃", "pinyin": "míhóutáo", "english": "Kiwifruit", "myanmar": "ကီဝီသီး"},
    {"chinese": "榴莲", "pinyin": "liúlián", "english": "Durian", "myanmar": "ဒူးရင်းသီး"},
    {"chinese": "山竹", "pinyin": "shānzhú", "english": "Mangosteen", "myanmar": "မင်းကွတ်သီး"},
    {"chinese": "荔枝", "pinyin": "lìzhī", "english": "Lychee", "myanmar": "လိုင်ချီးသီး"},
    {"chinese": "龙眼", "pinyin": "lóngyǎn", "english": "Longan", "myanmar": "လုံငန်းသီး"},
    {"chinese": "杨梅", "pinyin": "yángméi", "english": "Waxberry / Bayberry", "myanmar": "ရန်မေသီး"},
    {"chinese": "李子", "pinyin": "lǐzi", "english": "Plum", "myanmar": "ဇီးသီး"},
    {"chinese": "杏子", "pinyin": "xìngzi", "english": "Apricot", "myanmar": "အက်ပရီကော့သီး"},
    {"chinese": "梅子", "pinyin": "méizi", "english": "Mume plum", "myanmar": "ပလမ်သီး"},
    {"chinese": "枣", "pinyin": "zǎo", "english": "Jujube / Date", "myanmar": "တရုတ်ဆီးသီး"},
    {"chinese": "无花果", "pinyin": "wúhuāguǒ", "english": "Fig", "myanmar": "သင်္ဘောဆီးသီး"},
    {"chinese": "牛油果", "pinyin": "niúyóuguǒ", "english": "Avocado", "myanmar": "ထောပတ်သီး"},
    {"chinese": "百香果", "pinyin": "bǎixiāngguǒ", "english": "Passion fruit", "myanmar": "ပက်ရှင်ဖရု"},
    {"chinese": "番石榴", "pinyin": "fānshíliú", "english": "Guava", "myanmar": "မာလကာသီး"},
    {"chinese": "柚子", "pinyin": "yòuzi", "english": "Pomelo", "myanmar": "ကျွဲကောသီး"},
    {"chinese": "柑橘", "pinyin": "gānjú", "english": "Citrus", "myanmar": "ရှံသီး / လိမ္မော်မျိုးနွယ်"},
    {"chinese": "哈密瓜", "pinyin": "hāmìguā", "english": "Hami melon", "myanmar": "ဟာမီ ဖရဲမွှေး"},
    {"chinese": "甜瓜", "pinyin": "tiánguā", "english": "Muskmelon", "myanmar": "ဖရဲမွှေး"},
    {"chinese": "香瓜", "pinyin": "xiāngguā", "english": "Cantaloupe", "myanmar": "သခွားမွှေးသီး"},
    {"chinese": "黑莓", "pinyin": "hēiméi", "english": "Blackberry", "myanmar": "ဘလက်ဘယ်ရီ"},
    {"chinese": "蔓越莓", "pinyin": "mànyuèméi", "english": "Cranberry", "myanmar": "ခရမ်ဘယ်ရီ"},
    {"chinese": "桑葚", "pinyin": "sāngshèn", "english": "Mulberry", "myanmar": "ပိုးစာသီး"},
    {"chinese": "菠萝蜜", "pinyin": "bōluómì", "english": "Jackfruit", "myanmar": "ပိန္နဲသီး"},
    {"chinese": "莲雾", "pinyin": "liánwù", "english": "Wax apple", "myanmar": "ဇမ္ဗူသီး"},
    {"chinese": "杨桃", "pinyin": "yángtáo", "english": "Starfruit", "myanmar": "စောင်းလျားသီး"},
    {"chinese": "蛇皮果", "pinyin": "shépíguǒ", "english": "Salak / Snake fruit", "myanmar": "ပဲလင်းမြွေသီး"},
    {"chinese": "人心果", "pinyin": "rénxīnguǒ", "english": "Sapodilla", "myanmar": "သားလုံးသီး"},
    {"chinese": "释迦", "pinyin": "shìjiā", "english": "Sugar apple", "myanmar": "ဩဇာသီး"},
    {"chinese": "莲子", "pinyin": "liánzǐ", "english": "Lotus seed", "myanmar": "ပဒုမ္မာကြာစေ့"},
    {"chinese": "枇杷", "pinyin": "pípá", "english": "Loquat", "myanmar": "လူးခွတ်သီး"},
    {"chinese": "金桔", "pinyin": "jīnjú", "english": "Kumquat", "myanmar": "ကင်မုန်းသီး"},
    {"chinese": "橄榄", "pinyin": "gǎnlǎn", "english": "Olive", "myanmar": "သံလွင်သီး"},
    {"chinese": "青梅", "pinyin": "qīngméi", "english": "Green plum", "myanmar": "မက်မန်းသီးအစိမ်း"},
    {"chinese": "红毛丹", "pinyin": "hóngmáodān", "english": "Rambutan", "myanmar": "ကြက်မောက်သီး"},
    {"chinese": "神秘果", "pinyin": "shénmìguǒ", "english": "Miracle fruit", "myanmar": "မီးရက်ကယ်ဖရု"},
    {"chinese": "罗汉果", "pinyin": "luóhànguǒ", "english": "Monk fruit", "myanmar": "လိုဟန်ဂိုသီး"},
    {"chinese": "桑果", "pinyin": "sāngguǒ", "english": "Mulberry fruit", "myanmar": "ပိုးစာသီး"},
    {"chinese": "山楂", "pinyin": "shānzhā", "english": "Hawthorn", "myanmar": "စန်းကျားသီး"},
    {"chinese": "酸枣", "pinyin": "suānzǎo", "english": "Wild jujube", "myanmar": "ဆီးချဉ်သီး"},
    {"chinese": "沙棘", "pinyin": "shājí", "english": "Sea buckthorn", "myanmar": "ဆားငန်သီး"},
    {"chinese": "覆盆子", "pinyin": "fùpénzǐ", "english": "Raspberry", "myanmar": "ရက်စ်ဘယ်ရီ"},
    {"chinese": "黑加仑", "pinyin": "hēijiālún", "english": "Blackcurrant", "myanmar": "ဘလက်ကာရန့်"},
    {"chinese": "红加仑", "pinyin": "hóngjiālún", "english": "Redcurrant", "myanmar": "ရက်ဒ်ကာရန့်"},
    {"chinese": "醋栗", "pinyin": "cùlì", "english": "Gooseberry", "myanmar": "ဂူစဘယ်ရီ"},
    {"chinese": "榅桲", "pinyin": "wēnbó", "english": "Quince", "myanmar": "ကွင်စ့်သီး"},
    {"chinese": "榴莲蜜", "pinyin": "liúliánmì", "english": "Cempedak", "myanmar": "စမ်ပဒတ်သီး"},
    {"chinese": "番荔枝", "pinyin": "fānlìzhī", "english": "Custard apple", "myanmar": "ဩဇာသီး"},
    {"chinese": "毛荔枝", "pinyin": "máolìzhī", "english": "Rambutan / Hairy lychee", "myanmar": "ကြက်မောက်သီးအမွှေး"},
    {"chinese": "黄皮", "pinyin": "huángpí", "english": "Wampi", "myanmar": "ဝမ်ပီသီး"},
    {"chinese": "余甘子", "pinyin": "yúgānzǐ", "english": "Amla / Emblic", "myanmar": "ဆီးဖြူသီး"},
    {"chinese": "木莓", "pinyin": "mùméi", "english": "Bramble / Cloudberry", "myanmar": "တောဘယ်ရီသီး"},
    {"chinese": "黄桃", "pinyin": "huángtáo", "english": "Yellow peach", "myanmar": "အဝါရောင် မက်မွန်သီး"},
    {"chinese": "油桃", "pinyin": "yóutáo", "english": "Nectarine", "myanmar": "နက်ထရင်းသီး"},
    {"chinese": "蟠桃", "pinyin": "pántáo", "english": "Flat peach", "myanmar": "ပန်ထောင် မက်မွန်သီး"},
    {"chinese": "水蜜桃", "pinyin": "shuǐmìtáo", "english": "Honey peach", "myanmar": "အရည်ရွှမ်း မက်မွန်သီး"},
    {"chinese": "白桃", "pinyin": "báitáo", "english": "White peach", "myanmar": "အဖြူရောင် မက်မွန်သီး"},
    {"chinese": "青苹果", "pinyin": "qīngpíngguǒ", "english": "Green apple", "myanmar": "ပန်းသီးစိမ်း"},
    {"chinese": "红苹果", "pinyin": "hóngpíngguǒ", "english": "Red apple", "myanmar": "ပန်းသီးနီ"},
    {"chinese": "小番茄", "pinyin": "xiǎofānqié", "english": "Cherry tomato", "myanmar": "ချယ်ရီ ခရမ်းချဉ်သီး"},
    {"chinese": "甜橙", "pinyin": "tiánchéng", "english": "Sweet orange", "myanmar": "လိမ္မော်ချို"},
    {"chinese": "血橙", "pinyin": "xuèchéng", "english": "Blood orange", "myanmar": "သွေးလိမ္မော်"},
    {"chinese": "脐橙", "pinyin": "qíchéng", "english": "Navel orange", "myanmar": "နာဗဲလ်လိမ္မော်"},
    {"chinese": "柑", "pinyin": "gān", "english": "Mandarin orange", "myanmar": "ကမ္ဗလာသီး"},
    {"chinese": "蜜柑", "pinyin": "mìgān", "english": "Satsuma mandarin", "myanmar": "ပျားလိမ္မော်"},
    {"chinese": "椪柑", "pinyin": "pènggān", "english": "Ponkan mandarin", "myanmar": "ပုန်းကန်လိမ္မော်"},
    {"chinese": "葡萄柚", "pinyin": "pútáoyòu", "english": "Grapefruit", "myanmar": "ဂရေ့ဖရုသီး"},
    {"chinese": "青葡萄", "pinyin": "qīngpútáo", "english": "Green grape", "myanmar": "စပျစ်သီးစိမ်း"},
    {"chinese": "红葡萄", "pinyin": "hóngpútáo", "english": "Red grape", "myanmar": "စပျစ်သီးနီ"},
    {"chinese": "黑葡萄", "pinyin": "hēipútáo", "english": "Black grape", "myanmar": "စပျစ်သီးနက်"},
    {"chinese": "无籽西瓜", "pinyin": "wúzǐ xīguā", "english": "Seedless watermelon", "myanmar": "အစေ့မဲ့ ဖရဲသီး"},
    {"chinese": "香橙", "pinyin": "xiāngchéng", "english": "Yuzu", "myanmar": "ရနံ့သင်း လိမ္မော်သီး"},
    {"chinese": "椰枣", "pinyin": "yēzǎo", "english": "Date palm", "myanmar": "စွန်ပလုံသီး"},
    {"chinese": "仙人掌果", "pinyin": "xiānrénzhǎngguǒ", "english": "Cactus fruit / Prickly pear", "myanmar": "ရှားစောင်းလက်ပတ်သီး"},
    {"chinese": "蛇莓", "pinyin": "shéméi", "english": "Mock strawberry", "myanmar": "မော့ စတော်ဘယ်ရီ"},
    ],
  ),
  CategoryItem(
    emoji: "🍕🍟",
    titleEn: "Food",
    titleMy: "အစားအစာများ",
    words: [
      {"chinese": "米饭", "pinyin": "mǐfàn", "english": "Rice", "myanmar": "ထမင်း"},
    {"chinese": "面条", "pinyin": "miàntiáo", "english": "Noodles", "myanmar": "ခေါက်ဆွဲ"},
    {"chinese": "面包", "pinyin": "miànbāo", "english": "Bread", "myanmar": "ပေါင်မုန့်"},
    {"chinese": "馒头", "pinyin": "mántou", "english": "Steamed bun", "myanmar": "မန္တို (အစာမပါ ပေါက်စီ)"},
    {"chinese": "包子", "pinyin": "bāozi", "english": "Baozi / Stuffed bun", "myanmar": "ပေါက်စီ"},
    {"chinese": "饺子", "pinyin": "jiǎozi", "english": "Dumpling", "myanmar": "ကျောင်းဇိ (ဂျုံဒမ်ပလင်း)"},
    {"chinese": "粥", "pinyin": "zhōu", "english": "Porridge / Congee", "myanmar": "ဆန်ပြုတ်"},
    {"chinese": "炒饭", "pinyin": "chǎofàn", "english": "Fried rice", "myanmar": "ထမင်းကြော်"},
    {"chinese": "炒面", "pinyin": "chǎomiàn", "english": "Fried noodles", "myanmar": "ခေါက်ဆွဲကြော်"},
    {"chinese": "汤", "pinyin": "tāng", "english": "Soup", "myanmar": "ဟင်းချို / စープ"},
    {"chinese": "鸡蛋", "pinyin": "jīdàn", "english": "Egg", "myanmar": "ကြက်ဥ"},
    {"chinese": "鸡肉", "pinyin": "jīròu", "english": "Chicken meat", "myanmar": "ကြက်သား"},
    {"chinese": "牛肉", "pinyin": "niúròu", "english": "Beef", "myanmar": "အမဲသား"},
    {"chinese": "猪肉", "pinyin": "zhūròu", "english": "Pork", "myanmar": "ဝက်သား"},
    {"chinese": "羊肉", "pinyin": "yángròu", "english": "Mutton / Lamb", "myanmar": "ဆိတ်သား / သိုးသား"},
    {"chinese": "鱼", "pinyin": "yú", "english": "Fish", "myanmar": "ငါး"},
    {"chinese": "虾", "pinyin": "xiā", "english": "Shrimp / Prawn", "myanmar": "ပုစွန်"},
    {"chinese": "螃蟹", "pinyin": "pángxiè", "english": "Crab", "myanmar": "ဂဏန်း"},
    {"chinese": "豆腐", "pinyin": "dòufu", "english": "Tofu", "myanmar": "တို့ဟူး"},
    {"chinese": "蔬菜", "pinyin": "shūcài", "english": "Vegetables", "myanmar": "ဟင်းသီးဟင်းရွက်"},
    {"chinese": "白菜", "pinyin": "báicài", "english": "Chinese cabbage", "myanmar": "မုန်ညင်းဖြူ"},
    {"chinese": "生菜", "pinyin": "shēngcài", "english": "Lettuce", "myanmar": "ဆလတ်ရွက်"},
    {"chinese": "菠菜", "pinyin": "bōcài", "english": "Spinach", "myanmar": "ဟင်းနုနွယ်"},
    {"chinese": "胡萝卜", "pinyin": "húluóbo", "english": "Carrot", "myanmar": "မုန်လာဥနီ"},
    {"chinese": "土豆", "pinyin": "tǔdòu", "english": "Potato", "myanmar": "အာလူး"},
    {"chinese": "番茄", "pinyin": "fānqié", "english": "Tomato", "myanmar": "ခရမ်းချဉ်သီး"},
    {"chinese": "黄瓜", "pinyin": "huángguā", "english": "Cucumber", "myanmar": "သခွားသီး"},
    {"chinese": "洋葱", "pinyin": "yángcōng", "english": "Onion", "myanmar": "ကြက်သွန်နီ"},
    {"chinese": "玉米", "pinyin": "yùmǐ", "english": "Corn", "myanmar": "ပြောင်းဖူး"},
    {"chinese": "蘑菇", "pinyin": "mógū", "english": "Mushroom", "myanmar": "မှို"},
    {"chinese": "豆子", "pinyin": "dòuzi", "english": "Beans", "myanmar": "ပဲသီး / ပဲ"},
    {"chinese": "辣椒", "pinyin": "làjiāo", "english": "Chili", "myanmar": "ငရုတ်သီး"},
    {"chinese": "大蒜", "pinyin": "dàsuàn", "english": "Garlic", "myanmar": "ကြက်သွန်ဖြူ"},
    {"chinese": "姜", "pinyin": "jiāng", "english": "Ginger", "myanmar": "ဂျင်း"},
    {"chinese": "盐", "pinyin": "yán", "english": "Salt", "myanmar": "ဆား"},
    {"chinese": "糖", "pinyin": "táng", "english": "Sugar", "myanmar": "သကြား"},
    {"chinese": "油", "pinyin": "yóu", "english": "Oil", "myanmar": "ဆီ"},
    {"chinese": "醋", "pinyin": "cù", "english": "Vinegar", "myanmar": "ပုန်းရည်"},
    {"chinese": "酱油", "pinyin": "jiàngyóu", "english": "Soy sauce", "myanmar": "ပဲငံပြာရည်"},
    {"chinese": "辣椒酱", "pinyin": "làjiāojiàng", "english": "Chili sauce", "myanmar": "ငရုတ်သီးဆော့စ်"},
    {"chinese": "沙拉", "pinyin": "shālā", "english": "Salad", "myanmar": "ဆလတ်သုပ်"},
    {"chinese": "披萨", "pinyin": "pīsà", "english": "Pizza", "myanmar": "ပီဇာ"},
    {"chinese": "汉堡", "pinyin": "hànbǎo", "english": "Hamburger", "myanmar": "ဟမ်ဘာဂါ"},
    {"chinese": "三明治", "pinyin": "sānmíngzhì", "english": "Sandwich", "myanmar": "ဆန်းဒဝစ်ချ်"},
    {"chinese": "热狗", "pinyin": "règǒu", "english": "Hot dog", "myanmar": "ဟော့ဒေါ့ဂ်"},
    {"chinese": "薯条", "pinyin": "shǔtiáo", "english": "French fries", "myanmar": "အာလူးကြော်"},
    {"chinese": "蛋糕", "pinyin": "dàngāo", "english": "Cake", "myanmar": "ကိတ်မုန့်"},
    {"chinese": "饼干", "pinyin": "bǐnggān", "english": "Biscuit / Cookie", "myanmar": "ဘီစကစ်မုန့်"},
    {"chinese": "巧克力", "pinyin": "qiǎokèlì", "english": "Chocolate", "myanmar": "ချောကလက်"},
    {"chinese": "冰淇淋", "pinyin": "bīngqílín", "english": "Ice cream", "myanmar": "ရေခဲမုန့်"},
    {"chinese": "奶酪", "pinyin": "nǎilào", "english": "Cheese", "myanmar": "ဒိန်ခဲ"},
    {"chinese": "牛奶", "pinyin": "niúnǎi", "english": "Milk", "myanmar": "နွားနို့"},
    {"chinese": "酸奶", "pinyin": "suānnǎi", "english": "Yogurt", "myanmar": "ဒိန်ချဉ်"},
    {"chinese": "黄油", "pinyin": "huángyóu", "english": "Butter", "myanmar": "ထောပတ်"},
    {"chinese": "果酱", "pinyin": "guǒjiàng", "english": "Jam", "myanmar": "သစ်သီးယို"},
    {"chinese": "蜂蜜", "pinyin": "fēngmì", "english": "Honey", "myanmar": "ပျားရည်"},
    {"chinese": "花生", "pinyin": "huāshēng", "english": "Peanut", "myanmar": "မြေပဲ"},
    {"chinese": "花生酱", "pinyin": "huāshēngjiàng", "english": "Peanut butter", "myanmar": "မြေပဲထောပတ်"},
    {"chinese": "芝麻", "pinyin": "zhīma", "english": "Sesame", "myanmar": "နှမ်း"},
    {"chinese": "坚果", "pinyin": "jiānguǒ", "english": "Nuts", "myanmar": "အစေ့အဆန်များ"},
    {"chinese": "杏仁", "pinyin": "xìngrén", "english": "Almond", "myanmar": "ဗာဒံစေ့"},
    {"chinese": "核桃", "pinyin": "hétáo", "english": "Walnut", "myanmar": "သစ်ကြားသီး"},
    {"chinese": "腰果", "pinyin": "yāoguǒ", "english": "Cashew", "myanmar": "သီဟိုဠ်စေ့"},
    {"chinese": "开心果", "pinyin": "kāixīnguǒ", "english": "Pistachio", "myanmar": "ပစ်စတာချိုစေ့"},
    {"chinese": "瓜子", "pinyin": "guǎzǐ", "english": "Melon seeds", "myanmar": "ဖရဲစေ့"},
    {"chinese": "豆浆", "pinyin": "dòujiāng", "english": "Soy milk", "myanmar": "ပဲနို့"},
    {"chinese": "豆奶", "pinyin": "dòunǎi", "english": "Soy milk drink", "myanmar": "ပဲနို့အအေး"},
    {"chinese": "咖啡", "pinyin": "kāfēi", "english": "Coffee", "myanmar": "ကော်ဖီ"},
    {"chinese": "茶", "pinyin": "chá", "english": "Tea", "myanmar": "လက်ဖက်ရည် / ရေနွေးကြမ်း"},
    {"chinese": "果汁", "pinyin": "guǒzhī", "english": "Fruit juice", "myanmar": "အသီးဖျော်ရည်"},
    {"chinese": "汽水", "pinyin": "qìshuǐ", "english": "Soda / Soft drink", "myanmar": "အအေး (ဂက်စ်ပါ)"},
    {"chinese": "可乐", "pinyin": "kělè", "english": "Cola", "myanmar": "ကိုကာကိုလာ"},
    {"chinese": "果冻", "pinyin": "guǒdòng", "english": "Jelly", "myanmar": "ဂျယ်လီ"},
    {"chinese": "布丁", "pinyin": "bùdīng", "english": "Pudding", "myanmar": "ပူဒင်း"},
    {"chinese": "甜点", "pinyin": "tiándiǎn", "english": "Dessert", "myanmar": "အချိုမုန့် / အချိုပွဲ"},
    {"chinese": "蛋挞", "pinyin": "dàntà", "english": "Egg tart", "myanmar": "ကြက်ဥတားတ်"},
    {"chinese": "月饼", "pinyin": "yuèbǐng", "english": "Mooncake", "myanmar": "လမုန့်"},
    {"chinese": "粽子", "pinyin": "zòngzi", "english": "Zongzi / Rice dumpling", "myanmar": "ကောက်ညှင်းထုတ်"},
    {"chinese": "春卷", "pinyin": "chūnjuǎn", "english": "Spring roll", "myanmar": "ကော်ပြန့်ကြော်"},
    {"chinese": "煎饼", "pinyin": "jiānbǐng", "english": "Pancake", "myanmar": "ဂျုံပြားကြော်"},
    {"chinese": "油条", "pinyin": "yóutiáo", "english": "Deep-fried dough stick", "myanmar": "အီကြာကွေး"},
    {"chinese": "烧卖", "pinyin": "shāomài", "english": "Shumai", "myanmar": "ရှုမိုင်း"},
    {"chinese": "馄饨", "pinyin": "húntun", "english": "Wonton", "myanmar": "ဝမ်တန်"},
    {"chinese": "火锅", "pinyin": "huǒguō", "english": "Hot pot", "myanmar": "ဟော့ပေါ့"},
    {"chinese": "烤肉", "pinyin": "kǎoròu", "english": "BBQ / Roast meat", "myanmar": "အသားကင်"},
    {"chinese": "烤鱼", "pinyin": "kǎoyú", "english": "Grilled fish", "myanmar": "ငါးကင်"},
    {"chinese": "炸鸡", "pinyin": "zhájī", "english": "Fried chicken", "myanmar": "ကြက်ကြော်"},
    {"chinese": "寿司", "pinyin": "shòusī", "english": "Sushi", "myanmar": "ဆူရှီ"},
    {"chinese": "刺身", "pinyin": "cìshēn", "english": "Sashimi", "myanmar": "ဆာရှီမီ"},
    {"chinese": "咖喱", "pinyin": "gālí", "english": "Curry", "myanmar": "ကာရီ"},
    {"chinese": "意大利面", "pinyin": "yìdàlìmiàn", "english": "Spaghetti / Pasta", "myanmar": "စပါဂတီ / ပက်စတာ"},
    {"chinese": "牛排", "pinyin": "niúpái", "english": "Steak", "myanmar": "အမဲသားကင် (စတိတ်)"},
    {"chinese": "香肠", "pinyin": "xiāngcháng", "english": "Sausage", "myanmar": "ကြက်အူချောင်း"},
    {"chinese": "培根", "pinyin": "péigēn", "english": "Bacon", "myanmar": "ဘေကွန်"},
    {"chinese": "三文鱼", "pinyin": "sānwényú", "english": "Salmon", "myanmar": "ဆဲလ်မွန်ငါး"},
    {"chinese": "泡面", "pinyin": "pàomiàn", "english": "Instant noodles", "myanmar": "ခေါက်ဆွဲခြောက်"},
    {"chinese": "汤圆", "pinyin": "tāngyuán", "english": "Sweet rice balls", "myanmar": "ကောက်ညှင်းလုံး"},
    {"chinese": "绿茶", "pinyin": "lǜchá", "english": "Green tea", "myanmar": "လက်ဖက်ရည်စိမ်း"},
    {"chinese": "奶茶", "pinyin": "nǎichá", "english": "Milk tea", "myanmar": "လက်ဖက်ရည် / ဘာဘယ်တီ"},
    {"chinese": "啤酒", "pinyin": "píjiǔ", "english": "Beer", "myanmar": "ဘီယာ"},
    ],
  ),
  CategoryItem(
    emoji: "🤵👰",
    titleEn: "Family / People",
    titleMy: "မိသားစု / လူများ",
    words: [
      {"chinese": "爸爸", "pinyin": "bàba", "english": "Father / Dad", "myanmar": "ဖေဖေ"},
    {"chinese": "妈妈", "pinyin": "māma", "english": "Mother / Mom", "myanmar": "မေမေ"},
    {"chinese": "父亲", "pinyin": "fùqīn", "english": "Father (formal)", "myanmar": "အဖေ (တရားဝင်)"},
    {"chinese": "母亲", "pinyin": "mǔqīn", "english": "Mother (formal)", "myanmar": "အမေ (တရားဝင်)"},
    {"chinese": "儿子", "pinyin": "érzi", "english": "Son", "myanmar": "သား"},
    {"chinese": "女儿", "pinyin": "nǚ'ér", "english": "Daughter", "myanmar": "သမီး"},
    {"chinese": "哥哥", "pinyin": "gēge", "english": "Older brother", "myanmar": "အစ်ကို"},
    {"chinese": "姐姐", "pinyin": "jiějie", "english": "Older sister", "myanmar": "အစ်မ"},
    {"chinese": "弟弟", "pinyin": "dìdi", "english": "Younger brother", "myanmar": "မောင်လေး / ညီလေး"},
    {"chinese": "妹妹", "pinyin": "mèimei", "english": "Younger sister", "myanmar": "ညီမလေး / နှမလေး"},
    {"chinese": "爷爷", "pinyin": "yéye", "english": "Grandfather (Paternal)", "myanmar": "အဖိုး (အဖေဘက်)"},
    {"chinese": "奶奶", "pinyin": "nǎinai", "english": "Grandmother (Paternal)", "myanmar": "အဖွား (အဖေဘက်)"},
    {"chinese": "外公", "pinyin": "wàigōng", "english": "Grandfather (Maternal)", "myanmar": "အဖိုး (အမေဘက်)"},
    {"chinese": "外婆", "pinyin": "wàipó", "english": "Grandmother (Maternal)", "myanmar": "အဖွား (အမေဘက်)"},
    {"chinese": "叔叔", "pinyin": "shūshu", "english": "Uncle (Father's younger brother)", "myanmar": "ဦးလေး (အဖေ့ညီ)"},
    {"chinese": "阿姨", "pinyin": "āyí", "english": "Aunt (Mother's sister)", "myanmar": "အဒေါ် (အမေ့ညီမ)"},
    {"chinese": "伯伯", "pinyin": "bóbo", "english": "Uncle (Father's older brother)", "myanmar": "ဘကြီး"},
    {"chinese": "伯母", "pinyin": "bómǔ", "english": "Aunt (Father's older brother's wife)", "myanmar": "ဘကြီးကတော်"},
    {"chinese": "舅舅", "pinyin": "jiùjiu", "english": "Uncle (Mother's brother)", "myanmar": "ဦးလေး (အမေ့မောင်/အစ်ကို)"},
    {"chinese": "舅妈", "pinyin": "jiùmā", "english": "Aunt (Mother's brother's wife)", "myanmar": "အဒေါ် (အမေ့မောင်/အစ်ကို၏ဇနီး)"},
    {"chinese": "姑姑", "pinyin": "gūgu", "english": "Aunt (Father's sister)", "myanmar": "အဒေါ် (အဖေ့ညီမ/အစ်မ)"},
    {"chinese": "姑父", "pinyin": "gūfu", "english": "Uncle (Father's sister's husband)", "myanmar": "ဦးလေး (အဖေ့ညီမ/အစ်မ၏ခင်ပွန်း)"},
    {"chinese": "丈夫", "pinyin": "zhàngfu", "english": "Husband", "myanmar": "ခင်ပွန်း"},
    {"chinese": "妻子", "pinyin": "qīzi", "english": "Wife", "myanmar": "ဇနီး"},
    {"chinese": "老公", "pinyin": "lǎogōng", "english": "Husband (informal)", "myanmar": "အမျိုးသား / လင်ယောက်ျား"},
    {"chinese": "老婆", "pinyin": "lǎopó", "english": "Wife (informal)", "myanmar": "အမျိုးသမီး / မယား"},
    {"chinese": "孩子", "pinyin": "háizi", "english": "Child / Children", "myanmar": "ကလေး"},
    {"chinese": "男孩", "pinyin": "nánhái", "english": "Boy", "myanmar": "ယောက်ျားလေး"},
    {"chinese": "女孩", "pinyin": "nǚhái", "english": "Girl", "myanmar": "မိန်းကလေး"},
    {"chinese": "男人", "pinyin": "nánrén", "english": "Man", "myanmar": "ယောက်ျား"},
    {"chinese": "女人", "pinyin": "nǚrén", "english": "Woman", "myanmar": "မိန်းမ"},
    {"chinese": "朋友", "pinyin": "péngyou", "english": "Friend", "myanmar": "သူငယ်ချင်း"},
    {"chinese": "同学", "pinyin": "tóngxué", "english": "Classmate", "myanmar": "ကျောင်းနေဖက်"},
    {"chinese": "老师", "pinyin": "lǎoshī", "english": "Teacher", "myanmar": "ဆရာ / ဆရာမ"},
    {"chinese": "学生", "pinyin": "xuésheng", "english": "Student", "myanmar": "ကျောင်းသား / ကျောင်းသူ"},
    {"chinese": "医生", "pinyin": "yīshēng", "english": "Doctor", "myanmar": "ဆရာဝန်"},
    {"chinese": "护士", "pinyin": "hùshi", "english": "Nurse", "myanmar": "သူနာပြု"},
    {"chinese": "警察", "pinyin": "jǐngchá", "english": "Police officer", "myanmar": "ရဲ"},
    {"chinese": "司机", "pinyin": "sījī", "english": "Driver", "myanmar": "ယာဉ်မောင်း"},
    {"chinese": "厨师", "pinyin": "chúshī", "english": "Chef / Cook", "myanmar": "စားဖိုမှူး"},
    {"chinese": "服务员", "pinyin": "fúwùyuán", "english": "Waiter / Waitress", "myanmar": "စားပွဲထိုး"},
    {"chinese": "老板", "pinyin": "lǎobǎn", "english": "Boss", "myanmar": "သူဌေး / အလုပ်ရှင်"},
    {"chinese": "经理", "pinyin": "jīnglǐ", "english": "Manager", "myanmar": "မန်နေဂျာ"},
    {"chinese": "员工", "pinyin": "yuángōng", "english": "Employee / Staff", "myanmar": "ဝန်ထမ်း"},
    {"chinese": "工人", "pinyin": "gōngrén", "english": "Worker", "myanmar": "အလုပ်သမား"},
    {"chinese": "农民", "pinyin": "nóngmín", "english": "Farmer", "myanmar": "တောင်သူလယ်သမား"},
    {"chinese": "记者", "pinyin": "jìzhě", "english": "Journalist / Reporter", "myanmar": "သတင်းထောက်"},
    {"chinese": "演员", "pinyin": "yǎnyuán", "english": "Actor / Actress", "myanmar": "သရုပ်ဆောင်"},
    {"chinese": "歌手", "pinyin": "gēshǒu", "english": "Singer", "myanmar": "အဆိုတော်"},
    {"chinese": "画家", "pinyin": "huàjiā", "english": "Painter / Artist", "myanmar": "ပန်းချီဆရာ"},
    {"chinese": "作家", "pinyin": "zuòjiā", "english": "Writer / Author", "myanmar": "စာရေးဆရာ"},
    {"chinese": "运动员", "pinyin": "yùndòngyuán", "english": "Athlete", "myanmar": "အားကစားသမား"},
    {"chinese": "工程师", "pinyin": "gōngchéngshī", "english": "Engineer", "myanmar": "အင်ဂျင်နီယာ"},
    {"chinese": "程序员", "pinyin": "chéngxùyuán", "english": "Programmer", "myanmar": "ပရိုဂရမ်မာ"},
    {"chinese": "设计师", "pinyin": "shèjìshī", "english": "Designer", "myanmar": "ဒီဇိုင်နာ"},
    {"chinese": "律师", "pinyin": "lǜshī", "english": "Lawyer", "myanmar": "ရှေ့နေ"},
    {"chinese": "顾客", "pinyin": "gùkè", "english": "Customer", "myanmar": "ဝယ်သူ"},
    {"chinese": "客人", "pinyin": "kèrén", "english": "Guest", "myanmar": "ဧည့်သည်"},
    {"chinese": "邻居", "pinyin": "línjū", "english": "Neighbor", "myanmar": "အိမ်နီးနားချင်း"},
    {"chinese": "同事", "pinyin": "tóngshì", "english": "Colleague", "myanmar": "လုပ်ဖော်ကိုင်ဖက်"},
    {"chinese": "领导", "pinyin": "lǐngdǎo", "english": "Leader / Manager", "myanmar": "ခေါင်းဆောင် / လူကြီး"},
    {"chinese": "校长", "pinyin": "xiàozhǎng", "english": "Principal", "myanmar": "ကျောင်းအုပ်ဆရာကြီး"},
    {"chinese": "教授", "pinyin": "jiàoshòu", "english": "Professor", "myanmar": "ပါမောက္ခ"},
    {"chinese": "外国人", "pinyin": "wàiguórén", "english": "Foreigner", "myanmar": "နိုင်ငံခြားသား"},
    {"chinese": "中国人", "pinyin": "zhōngguórén", "english": "Chinese person", "myanmar": "တရုတ်လူမျိုး"},
    {"chinese": "日本人", "pinyin": "rìběnrén", "english": "Japanese person", "myanmar": "ဂျပန်လူမျိုး"},
    {"chinese": "韩国人", "pinyin": "hánguórén", "english": "Korean person", "myanmar": "ကိုရီးယားလူမျိုး"},
    {"chinese": "美国人", "pinyin": "měiguórén", "english": "American person", "myanmar": "အမေရိကန်လူမျိုး"},
    {"chinese": "英国人", "pinyin": "yīngguórén", "english": "British person", "myanmar": "အင်္ဂလိပ်လူမျိုး"},
    {"chinese": "老人", "pinyin": "lǎorén", "english": "Elderly person", "myanmar": "သက်ကြီးရွယ်အို"},
    {"chinese": "年轻人", "pinyin": "niánqīngrén", "english": "Young person", "myanmar": "လူငယ်"},
    {"chinese": "成年人", "pinyin": "chéngniánrén", "english": "Adult", "myanmar": "လူကြီး (အရွယ်ရောက်ပြီးသူ)"},
    {"chinese": "儿童", "pinyin": "értóng", "english": "Children", "myanmar": "ကလေးငယ်"},
    {"chinese": "婴儿", "pinyin": "yīng'ér", "english": "Infant / Baby", "myanmar": "မွေးကင်းစကလေး"},
    {"chinese": "宝宝", "pinyin": "bǎobao", "english": "Baby", "myanmar": "ကလေးလေး / ဘေဘီ"},
    {"chinese": "少年", "pinyin": "shàonián", "english": "Teenager", "myanmar": "လူငယ်"},
    {"chinese": "少女", "pinyin": "shàonǚ", "english": "Young girl", "myanmar": "မိန်းကလေးငယ်"},
    {"chinese": "青年", "pinyin": "qīngnián", "english": "Youth", "myanmar": "လူငယ်ပိုင်း"},
    {"chinese": "家人", "pinyin": "jiārén", "english": "Family members", "myanmar": "မိသားစုဝင်များ"},
    {"chinese": "亲戚", "pinyin": "qīnqi", "english": "Relatives", "myanmar": "ဆွေမျိုး"},
    {"chinese": "亲人", "pinyin": "qīnrén", "english": "Loved ones / Relatives", "myanmar": "မိသားစု/ဆွေမျိုး"},
    {"chinese": "夫妻", "pinyin": "fūqī", "english": "Husband and wife", "myanmar": "ဇနီးမောင်နှံ"},
    {"chinese": "父母", "pinyin": "fùmǔ", "english": "Parents", "myanmar": "မိဘများ"},
    {"chinese": "兄弟", "pinyin": "xiōngdì", "english": "Brothers", "myanmar": "ညီအစ်ကိုများ"},
    {"chinese": "姐妹", "pinyin": "jiěmèi", "english": "Sisters", "myanmar": "ညီအစ်မများ"},
    {"chinese": "祖父", "pinyin": "zǔfù", "english": "Grandfather", "myanmar": "အဖိုး (တရားဝင်)"},
    {"chinese": "祖母", "pinyin": "zǔmǔ", "english": "Grandmother", "myanmar": "အဖွား (တရားဝင်)"},
    {"chinese": "孙子", "pinyin": "sūnzi", "english": "Grandson", "myanmar": "မြေးယောက်ျားလေး"},
    {"chinese": "孙女", "pinyin": "sūnnǚ", "english": "Granddaughter", "myanmar": "မြေးမိန်းကလေး"},
    {"chinese": "侄子", "pinyin": "zhízi", "english": "Nephew (Brother's son)", "myanmar": "တူ (အစ်ကို/ညီ၏သား)"},
    {"chinese": "侄女", "pinyin": "zhí nǚ", "english": "Niece (Brother's daughter)", "myanmar": "တူမ (အစ်ကို/ညီ၏သမီး)"},
    {"chinese": "外甥", "pinyin": "wàishēng", "english": "Nephew (Sister's son)", "myanmar": "တူ (အစ်မ/ညီမ၏သား)"},
    {"chinese": "主人", "pinyin": "zhǔrén", "english": "Host / Owner", "myanmar": "အိမ်ရှင် / ပိုင်ရှင်"},
    {"chinese": "军人", "pinyin": "jūnrén", "english": "Soldier", "myanmar": "စစ်သား"},
    {"chinese": "陌生人", "pinyin": "mòshēngrén", "english": "Stranger", "myanmar": "သူစိမ်း"},
    {"chinese": "飞行员", "pinyin": "fēixíngyuán", "english": "Pilot", "myanmar": "လေယာဉ်မောင်း"},
    {"chinese": "伙伴", "pinyin": "huǒbàn", "english": "Partner / Companion", "myanmar": "အပေါင်းအသင်း"},
    {"chinese": "同伴", "pinyin": "tóngbàn", "english": "Companion", "myanmar": "အဖော်"},
    {"chinese": "助手", "pinyin": "zhùshǒu", "english": "Assistant", "myanmar": "အကူ / လက်ထောက်"},
    {"chinese": "科学家", "pinyin": "kēxuéjiā", "english": "Scientist", "myanmar": "သိပ္ပံပညာရှင်"},
    ],
  ),
  CategoryItem(
    emoji: "🏙",
    titleEn: "School",
    titleMy: "ကျောင်း",
    words: [
      {"chinese": "学校", "pinyin": "xuéxiào", "english": "School", "myanmar": "ကျောင်း"},
    {"chinese": "教室", "pinyin": "jiàoshì", "english": "Classroom", "myanmar": "စာသင်ခန်း"},
    {"chinese": "老师", "pinyin": "lǎoshī", "english": "Teacher", "myanmar": "ဆရာ / ဆရာမ"},
    {"chinese": "学生", "pinyin": "xuésheng", "english": "Student", "myanmar": "ကျောင်းသား / ကျောင်းသူ"},
    {"chinese": "同学", "pinyin": "tóngxué", "english": "Classmate", "myanmar": "ကျောင်းနေဖက်"},
    {"chinese": "校长", "pinyin": "xiàozhǎng", "english": "Principal / Headmaster", "myanmar": "ကျောင်းအုပ်ဆရာကြီး"},
    {"chinese": "课本", "pinyin": "kèběn", "english": "Textbook", "myanmar": "သင်ရိုးဖတ်စာအုပ်"},
    {"chinese": "书", "pinyin": "shū", "english": "Book", "myanmar": "စာအုပ်"},
    {"chinese": "笔", "pinyin": "bǐ", "english": "Pen", "myanmar": "ကလောင်တံ / ဘောပင်"},
    {"chinese": "铅笔", "pinyin": "qiānbǐ", "english": "Pencil", "myanmar": "ခဲတံ"},
    {"chinese": "橡皮", "pinyin": "xiàngpí", "english": "Eraser", "myanmar": "ခဲဖျက်"},
    {"chinese": "尺子", "pinyin": "chǐzi", "english": "Ruler", "myanmar": "ပေတံ"},
    {"chinese": "书包", "pinyin": "shūbāo", "english": "Schoolbag", "myanmar": "စာအုပ်လွယ်အိတ်"},
    {"chinese": "黑板", "pinyin": "hēibǎn", "english": "Blackboard", "myanmar": "သင်ပုန်းနက်"},
    {"chinese": "白板", "pinyin": "báibǎn", "english": "Whiteboard", "myanmar": "ဝှိုက်ဘုတ်"},
    {"chinese": "粉笔", "pinyin": "fěnbǐ", "english": "Chalk", "myanmar": "မြေဖြူ"},
    {"chinese": "桌子", "pinyin": "zhuōzi", "english": "Desk / Table", "myanmar": "စာပွဲ"},
    {"chinese": "椅子", "pinyin": "yǐzi", "english": "Chair", "myanmar": "ကုလားထိုင်"},
    {"chinese": "教科书", "pinyin": "jiàokēshū", "english": "Textbook", "myanmar": "သင်ရိုးစာအုပ်"},
    {"chinese": "字典", "pinyin": "zìdiǎn", "english": "Dictionary", "myanmar": "အဘိဓာန်"},
    {"chinese": "作业", "pinyin": "zuòyè", "english": "Homework", "myanmar": "အိမ်စာ"},
    {"chinese": "考试", "pinyin": "kǎoshì", "english": "Exam / Test", "myanmar": "စာမေးပွဲ"},
    {"chinese": "考卷", "pinyin": "kǎojuàn", "english": "Exam paper", "myanmar": "စာမေးပွဲမေးခွန်းစာရွက်"},
    {"chinese": "问题", "pinyin": "wèntí", "english": "Question / Problem", "myanmar": "မေးခွန်း / ပြဿနာ"},
    {"chinese": "答案", "pinyin": "dá'àn", "english": "Answer", "myanmar": "အဖြေ"},
    {"chinese": "课程", "pinyin": "kèchéng", "english": "Course / Curriculum", "myanmar": "သင်ရိုးညွှန်းတမ်း / ဘာသာရပ်"},
    {"chinese": "数学", "pinyin": "shùxué", "english": "Mathematics", "myanmar": "သင်္ချာ"},
    {"chinese": "中文", "pinyin": "zhōngwén", "english": "Chinese language", "myanmar": "တရုတ်စာ"},
    {"chinese": "英语", "pinyin": "yīngyǔ", "english": "English language", "myanmar": "အင်္ဂလိပ်စာ"},
    {"chinese": "科学", "pinyin": "kēxué", "english": "Science", "myanmar": "သိပ္ပံ"},
    {"chinese": "历史", "pinyin": "lìshǐ", "english": "History", "myanmar": "သမိုင်း"},
    {"chinese": "地理", "pinyin": "dìlǐ", "english": "Geography", "myanmar": "ပထဝီ"},
    {"chinese": "音乐", "pinyin": "yīnyuè", "english": "Music", "myanmar": "ဂီတ"},
    {"chinese": "美术", "pinyin": "měishù", "english": "Art", "myanmar": "ပန်းချီ / အနုပညာ"},
    {"chinese": "体育", "pinyin": "tǐyù", "english": "Physical Education (PE)", "myanmar": "ကာယပညာ"},
    {"chinese": "电脑", "pinyin": "diànnǎo", "english": "Computer", "myanmar": "ကွန်ပျူတာ"},
    {"chinese": "图书馆", "pinyin": "túshūguǎn", "english": "Library", "myanmar": "စာကြည့်တိုက်"},
    {"chinese": "实验室", "pinyin": "shíyànshì", "english": "Laboratory", "myanmar": "ဓာတ်ခွဲခန်း"},
    {"chinese": "操场", "pinyin": "cāochǎng", "english": "Playground / Sports field", "myanmar": "အားကစားကွင်း"},
    {"chinese": "食堂", "pinyin": "shítáng", "english": "Cafeteria / Canteen", "myanmar": "ကန်တင်း / စားသောက်ခန်း"},
    {"chinese": "校服", "pinyin": "xiàofú", "english": "School uniform", "myanmar": "ကျောင်းဝတ်စုံ"},
    {"chinese": "校园", "pinyin": "xiàoyuán", "english": "Campus", "myanmar": "ကျောင်းဝင်း"},
    {"chinese": "班级", "pinyin": "bānjí", "english": "Class", "myanmar": "အတန်း"},
    {"chinese": "年级", "pinyin": "niánjí", "english": "Grade / Year", "myanmar": "အတန်း (၁ တန်း၊ ၂ တန်း)"},
    {"chinese": "大学", "pinyin": "dàxué", "english": "University", "myanmar": "တက္ကသိုလ်"},
    {"chinese": "大学生", "pinyin": "dàxuésheng", "english": "University student", "myanmar": "တက္ကသိုလ်ကျောင်းသား"},
    {"chinese": "教授", "pinyin": "jiàoshòu", "english": "Professor", "myanmar": "ပါမောက္ခ"},
    {"chinese": "学习", "pinyin": "xuéxí", "english": "Study / Learn", "myanmar": "လေ့လာသည် / စာကျက်သည်"},
    {"chinese": "读书", "pinyin": "dúshū", "english": "Read / Study", "myanmar": "စာဖတ်သည် / စာသင်သည်"},
    {"chinese": "写字", "pinyin": "xiězì", "english": "Write characters", "myanmar": "စာရေးသည်"},
    {"chinese": "阅读", "pinyin": "yuèdú", "english": "Reading", "myanmar": "စာဖတ်ခြင်း"},
    {"chinese": "练习", "pinyin": "liànxí", "english": "Practice / Exercise", "myanmar": "လေ့ကျင့်သည်"},
    {"chinese": "复习", "pinyin": "fùxí", "english": "Review / Revise", "myanmar": "စာပြန်နွှေးသည်"},
    {"chinese": "预习", "pinyin": "yùxí", "english": "Preview", "myanmar": "ကြိုတင်လေ့လာသည်"},
    {"chinese": "上课", "pinyin": "shàngkè", "english": "Attend class", "myanmar": "စာသင်တက်သည်"},
    {"chinese": "下课", "pinyin": "xiàkè", "english": "Class dismissed", "myanmar": "အတန်းဆင်းသည်"},
    {"chinese": "放学", "pinyin": "fàngxué", "english": "School ends", "myanmar": "ကျောင်းဆင်းသည်"},
    {"chinese": "毕业", "pinyin": "bìyè", "english": "Graduation / Graduate", "myanmar": "ကျောင်းဆင်းသည် / ဘွဲ့ရသည်"},
    {"chinese": "文具", "pinyin": "wénjù", "english": "Stationery", "myanmar": "စာရေးကိရိယာ"},
    {"chinese": "纸", "pinyin": "zhǐ", "english": "Paper", "myanmar": "စာရွက်"},
    {"chinese": "本子", "pinyin": "běnzi", "english": "Notebook", "myanmar": "ဗာဟိယာစာအုပ်"},
    {"chinese": "笔记本", "pinyin": "bǐjìběn", "english": "Notebook", "myanmar": "မှတ်စုစာအုပ်"},
    {"chinese": "钢笔", "pinyin": "gāngbǐ", "english": "Fountain pen", "myanmar": "မင်စက်ဖောင်တိန်"},
    {"chinese": "彩笔", "pinyin": "cǎibǐ", "english": "Color pen / Marker", "myanmar": "ဆေးရောင်စုံဖောင်တိန်"},
    {"chinese": "书架", "pinyin": "shūjià", "english": "Bookshelf", "myanmar": "စာအုပ်စင်"},
    {"chinese": "地图", "pinyin": "dìtú", "english": "Map", "myanmar": "မြေပုံ"},
    {"chinese": "地球仪", "pinyin": "dìqiúyí", "english": "Globe", "myanmar": "ကမ္ဘာလုံး"},
    {"chinese": "电脑室", "pinyin": "diànnǎoshì", "english": "Computer room", "myanmar": "ကွန်ပျူတာခန်း"},
    {"chinese": "办公室", "pinyin": "bàngōngshì", "english": "Office", "myanmar": "ရုံးခန်း"},
    {"chinese": "教学", "pinyin": "jiàoxué", "english": "Teaching", "myanmar": "သင်ကြားရေး"},
    {"chinese": "知识", "pinyin": "zhīshi", "english": "Knowledge", "myanmar": "အသိပညာ / ဗဟုသုတ"},
    {"chinese": "语言", "pinyin": "yǔyán", "english": "Language", "myanmar": "ဘာသာစကား"},
    {"chinese": "汉字", "pinyin": "hànzì", "english": "Chinese character", "myanmar": "တရုတ်စာလုံး"},
    {"chinese": "拼音", "pinyin": "pīnyīn", "english": "Pinyin", "myanmar": "ပင်းယင်း (အသံထွက်စနစ်)"},
    {"chinese": "单词", "pinyin": "dāncí", "english": "Word / Vocabulary", "myanmar": "ဝေါဟာရ / စကားလုံး"},
    {"chinese": "句子", "pinyin": "jùzi", "english": "Sentence", "myanmar": "ဝါကျ"},
    {"chinese": "语法", "pinyin": "yǔfǎ", "english": "Grammar", "myanmar": "သဒ္ဒါ"},
    {"chinese": "发音", "pinyin": "fāyīn", "english": "Pronunciation", "myanmar": "အသံထွက်"},
    {"chinese": "成绩", "pinyin": "chéngjì", "english": "Grade / Academic result", "myanmar": "စာမေးပွဲရလဒ်"},
    {"chinese": "分数", "pinyin": "fēnshù", "english": "Score / Mark", "myanmar": "အမှတ်"},
    {"chinese": "奖品", "pinyin": "jiǎngpǐn", "english": "Prize / Reward", "myanmar": "ဆု"},
    {"chinese": "奖学金", "pinyin": "jiǎngxuéjīn", "english": "Scholarship", "myanmar": "ပညာသင်ဆု"},
    {"chinese": "比赛", "pinyin": "bǐsài", "english": "Competition / Match", "myanmar": "ပြိုင်ပွဲ"},
    {"chinese": "活动", "pinyin": "huódòng", "english": "Activity", "myanmar": "လှုပ်ရှားမှု / ပွဲ"},
    {"chinese": "体育馆", "pinyin": "tǐyùguǎn", "english": "Gymnasium", "myanmar": "အားကစားရုံ"},
    {"chinese": "游泳池", "pinyin": "yóuyǒngchí", "english": "Swimming pool", "myanmar": "ရေကူးကန်"},
    {"chinese": "校车", "pinyin": "xiàochē", "english": "School bus", "myanmar": "ကျောင်းကား"},
    {"chinese": "校门", "pinyin": "xiàomén", "english": "School gate", "myanmar": "ကျောင်းတံခါး"},
    {"chinese": "教学楼", "pinyin": "jiàoxuélóu", "english": "Teaching building", "myanmar": "စာသင်ဆောင်"},
    {"chinese": "宿舍", "pinyin": "sùshè", "english": "Dormitory", "myanmar": "အဆောင်"},
    {"chinese": "学位", "pinyin": "xuéwèi", "english": "Academic degree", "myanmar": "ဘွဲ့"},
    {"chinese": "专业", "pinyin": "zhuānyè", "english": "Major / Specialization", "myanmar": "အဓိကဘာသာရပ် (မေဂျာ)"},
    {"chinese": "学期", "pinyin": "xuéqī", "english": "Semester / Term", "myanmar": "စာသင်နှစ်ဝက်"},
    {"chinese": "毕业证", "pinyin": "bìyèzhèng", "english": "Graduation diploma", "myanmar": "ဘွဲ့လက်မှတ် / ကျောင်းဆင်းလက်မှတ်"},
    {"chinese": "课表", "pinyin": "kèbiǎo", "english": "Class timetable", "myanmar": "အတန်းချိန်ဇယား"},
    {"chinese": "课堂", "pinyin": "kètáng", "english": "Classroom session", "myanmar": "အတန်း / သင်တန်းခန်းမ"},
    {"chinese": "校园卡", "pinyin": "xiàoyuánkǎ", "english": "Campus card", "myanmar": "ကျောင်းသားကတ်"},
    {"chinese": "校徽", "pinyin": "xiàohuī", "english": "School badge", "myanmar": "ကျောင်းတံဆိပ်"},
    {"chinese": "校刊", "pinyin": "xiàokān", "english": "School magazine", "myanmar": "ကျောင်းမဂ္ဂဇင်း"},
    {"chinese": "校报", "pinyin": "xiàobào", "english": "School newspaper", "myanmar": "ကျောင်းသတင်းစာ"},
    ],
  ),
  CategoryItem(
    emoji: "🚖",
    titleEn: "Transport",
    titleMy: "သယ်ယူပို့ဆောင်ရေး",
    words: [
      {"chinese": "汽车", "pinyin": "qìchē", "english": "Car / Automobile", "myanmar": "ကား"},
    {"chinese": "小汽车", "pinyin": "xiǎoqìchē", "english": "Small car / Sedan", "myanmar": "ကားအသေး"},
    {"chinese": "公共汽车", "pinyin": "gōnggòng qìchē", "english": "Bus", "myanmar": "လိုင်းကား / ဘတ်စ်ကား"},
    {"chinese": "公交车", "pinyin": "gōngjiāochē", "english": "City bus", "myanmar": "မြို့တွင်းဘတ်စ်ကား"},
    {"chinese": "出租车", "pinyin": "chūzūchē", "english": "Taxi", "myanmar": "တက္ကစီ"},
    {"chinese": "火车", "pinyin": "huǒchē", "english": "Train", "myanmar": "ရထား"},
    {"chinese": "高铁", "pinyin": "gāotiě", "english": "High-speed train", "myanmar": "အမြန်ရထား"},
    {"chinese": "地铁", "pinyin": "dìtiě", "english": "Subway / Metro", "myanmar": "မြေအောက်ရထား"},
    {"chinese": "飞机", "pinyin": "fēijī", "english": "Airplane", "myanmar": "လေယာဉ်ပျံ"},
    {"chinese": "船", "pinyin": "chuán", "english": "Boat / Ship", "myanmar": "လှေ / သင်္ဘော"},
    {"chinese": "轮船", "pinyin": "lúnchuán", "english": "Steamship / Ship", "myanmar": "သင်္ဘော"},
    {"chinese": "快艇", "pinyin": "kuàitǐng", "english": "Speedboat", "myanmar": "အမြန်စက်လှေ"},
    {"chinese": "自行车", "pinyin": "zìxíngchē", "english": "Bicycle", "myanmar": "စက်ဘီး"},
    {"chinese": "摩托车", "pinyin": "mótuōchē", "english": "Motorcycle", "myanmar": "ဆိုင်ကယ်"},
    {"chinese": "电动车", "pinyin": "diàndòngchē", "english": "Electric vehicle", "myanmar": "လျှပ်စစ်ကား / အီးဘိုက်"},
    {"chinese": "卡车", "pinyin": "kǎchē", "english": "Truck", "myanmar": "ထရပ်ကား"},
    {"chinese": "货车", "pinyin": "huòchē", "english": "Freight truck / Lorry", "myanmar": "ကုန်တင်ကား"},
    {"chinese": "救护车", "pinyin": "jiùhùchē", "english": "Ambulance", "myanmar": "လူနာတင်ယာဉ်"},
    {"chinese": "消防车", "pinyin": "xiāofángchē", "english": "Fire engine", "myanmar": "မီးသတ်ကား"},
    {"chinese": "警车", "pinyin": "jǐngchē", "english": "Police car", "myanmar": "ရဲကား"},
    {"chinese": "校车", "pinyin": "xiàochē", "english": "School bus", "myanmar": "ကျောင်းကား"},
    {"chinese": "巴士", "pinyin": "bāshì", "english": "Bus", "myanmar": "ဘတ်စ်ကား"},
    {"chinese": "电车", "pinyin": "diànchē", "english": "Tram / Trolleybus", "myanmar": "ဓာတ်ရထား"},
    {"chinese": "有轨电车", "pinyin": "yǒuguǐ diànchē", "english": "Tram / Streetcar", "myanmar": "လမ်းကြောင်းရှိ ဓာတ်ရထား"},
    {"chinese": "轻轨", "pinyin": "qīngguǐ", "english": "Light rail", "myanmar": "လျှပ်စစ်ရထားလိုင်း"},
    {"chinese": "火车站", "pinyin": "huǒchēzhàn", "english": "Train station", "myanmar": "ရထားဘူတာ"},
    {"chinese": "机场", "pinyin": "jīchǎng", "english": "Airport", "myanmar": "လေဆိပ်"},
    {"chinese": "港口", "pinyin": "gǎngkǒu", "english": "Port / Harbor", "myanmar": "သင်္ဘောဆိပ် / ဆိပ်ကမ်း"},
    {"chinese": "车站", "pinyin": "chēzhàn", "english": "Station / Stop", "myanmar": "ကားဂိတ် / ဘူတာ"},
    {"chinese": "码头", "pinyin": "mǎtou", "english": "Pier / Dock", "myanmar": "သင်္ဘောဆိပ်ဂိတ်"},
    {"chinese": "车", "pinyin": "chē", "english": "Vehicle / Car", "myanmar": "ယာဉ် / ကား"},
    {"chinese": "轮胎", "pinyin": "lúntāi", "english": "Tire", "myanmar": "တာယာ"},
    {"chinese": "方向盘", "pinyin": "fāngxiàngpán", "english": "Steering wheel", "myanmar": "စတီယာရင်"},
    {"chinese": "刹车", "pinyin": "shāchē", "english": "Brake", "myanmar": "ဘရိတ်"},
    {"chinese": "发动机", "pinyin": "fādòngjī", "english": "Engine", "myanmar": "အင်ဂျင်"},
    {"chinese": "汽油", "pinyin": "qìyóu", "english": "Gasoline / Petrol", "myanmar": "ဓာတ်ဆီ"},
    {"chinese": "电池", "pinyin": "diànchí", "english": "Battery", "myanmar": "ဘက်ထရီ"},
    {"chinese": "司机", "pinyin": "sījī", "english": "Driver", "myanmar": "ယာဉ်မောင်း"},
    {"chinese": "乘客", "pinyin": "chéngkè", "english": "Passenger", "myanmar": "ခရီးသည်"},
    {"chinese": "票", "pinyin": "piào", "english": "Ticket", "myanmar": "လက်မှတ်"},
    {"chinese": "车票", "pinyin": "chēpiào", "english": "Train / Bus ticket", "myanmar": "ကား/ရထား လက်မှတ်"},
    {"chinese": "机票", "pinyin": "jīpiào", "english": "Flight ticket", "myanmar": "လေယာဉ်လက်မှတ်"},
    {"chinese": "船票", "pinyin": "chuánpiào", "english": "Ship ticket", "myanmar": "သင်္ဘောလက်မှတ်"},
    {"chinese": "公路", "pinyin": "gōnglù", "english": "Highway / Road", "myanmar": "ကားလမ်းမ"},
    {"chinese": "马路", "pinyin": "mǎlù", "english": "Road / Street", "myanmar": "လမ်းမ"},
    {"chinese": "高速公路", "pinyin": "gāosù gōnglù", "english": "Expressway", "myanmar": "အမြန်လမ်းမကြီး"},
    {"chinese": "桥", "pinyin": "qiáo", "english": "Bridge", "myanmar": "တံတား"},
    {"chinese": "隧道", "pinyin": "suìdào", "english": "Tunnel", "myanmar": "လိုဏ်ခေါင်း"},
    {"chinese": "红绿灯", "pinyin": "hónglǜdēng", "english": "Traffic light", "myanmar": "မီးပွိုင့်"},
    {"chinese": "斑马线", "pinyin": "bānmǎxiàn", "english": "Zebra crossing", "myanmar": "လူကူးမျဉ်းကျား"},
    {"chinese": "停车场", "pinyin": "tíngchēchǎng", "english": "Parking lot", "myanmar": "ကားရပ်နားစခန်း"},
    {"chinese": "加油站", "pinyin": "jiāyóuzhàn", "english": "Gas station", "myanmar": "ဓာတ်ဆီဆိုင်"},
    {"chinese": "地铁站", "pinyin": "dìtiězhàn", "english": "Subway station", "myanmar": "မြေအောက်ရထားဘူတာ"},
    {"chinese": "公交站", "pinyin": "gōngjiāozhàn", "english": "Bus stop", "myanmar": "ဘတ်စ်ကားဂိတ်"},
    {"chinese": "站台", "pinyin": "zhàntái", "english": "Platform", "myanmar": "ဘူတာရုံ ပလက်ဖောင်း"},
    {"chinese": "车门", "pinyin": "chēmén", "english": "Vehicle door", "myanmar": "ကားတံခါး"},
    {"chinese": "车窗", "pinyin": "chēchuāng", "english": "Vehicle window", "myanmar": "ကားပြတင်းပေါက်"},
    {"chinese": "安全带", "pinyin": "ānquándài", "english": "Seat belt", "myanmar": "ထိုင်ခုံခါးပတ်"},
    {"chinese": "头盔", "pinyin": "tóukuī", "english": "Helmet", "myanmar": "ဆိုင်ကယ်စီးဦးထုပ်"},
    {"chinese": "路线", "pinyin": "lùxiàn", "english": "Route", "myanmar": "လမ်းကြောင်း"},
    {"chinese": "方向", "pinyin": "fāngxiàng", "english": "Direction", "myanmar": "ဦးတည်ရာ / အရပ်မျက်နှာ"},
    {"chinese": "旅行", "pinyin": "lǚxíng", "english": "Travel / Journey", "myanmar": "ခရီးသွားခြင်း"},
    {"chinese": "旅游车", "pinyin": "lǚyóuchē", "english": "Tour bus", "myanmar": "ခရီးသွားဘတ်စ်ကား"},
    {"chinese": "房车", "pinyin": "fángchē", "english": "RV / Motorhome", "myanmar": "မော်တော်အိမ်ကား"},
    {"chinese": "赛车", "pinyin": "sàichē", "english": "Racing car", "myanmar": "ပြိုင်ကား"},
    {"chinese": "敞篷车", "pinyin": "chǎngpéngchē", "english": "Convertible", "myanmar": "အမိုးဖွင့်ကား"},
    {"chinese": "卡丁车", "pinyin": "kǎdīngchē", "english": "Go-kart", "myanmar": "ဂိုကတ်ကား"},
    {"chinese": "拖拉机", "pinyin": "tuōlājī", "english": "Tractor", "myanmar": "ထရက်တာ"},
    {"chinese": "起重机", "pinyin": "qǐzhòngjī", "english": "Crane", "myanmar": "ကရိန်းကား"},
    {"chinese": "挖掘机", "pinyin": "wājuéjī", "english": "Excavator", "myanmar": "မြေကျင်းတူးစက်"},
    {"chinese": "直升机", "pinyin": "zhíshēngjī", "english": "Helicopter", "myanmar": "ဟယ်လီကော်ပတာ"},
    {"chinese": "火箭", "pinyin": "huǒjiàn", "english": "Rocket", "myanmar": "ဒုံးပျံ"},
    {"chinese": "热气球", "pinyin": "rèqìqiú", "english": "Hot air balloon", "myanmar": "မီးပူဘောလုံး"},
    {"chinese": "缆车", "pinyin": "lǎnchē", "english": "Cable car", "myanmar": "ကေဘယ်ကြိုးတွဲ"},
    {"chinese": "独木舟", "pinyin": "dúmùzhōu", "english": "Canoe", "myanmar": "သစ်လုံးလှေ"},
    {"chinese": "帆船", "pinyin": "fānchuán", "english": "Sailboat", "myanmar": "ရွက်လှေ"},
    {"chinese": "游艇", "pinyin": "yóutǐng", "english": "Yacht", "myanmar": "ယacht သင်္ဘော"},
    {"chinese": "潜水艇", "pinyin": "qiánshuǐtǐng", "english": "Submarine", "myanmar": "ရေငုပ်သင်္ဘော"},
    {"chinese": "渡轮", "pinyin": "dùlún", "english": "Ferry", "myanmar": "ကူးတို့သင်္ဘော"},
    {"chinese": "货轮", "pinyin": "huòlún", "english": "Cargo ship", "myanmar": "ကုန်တင်သင်္ဘော"},
    {"chinese": "邮轮", "pinyin": "yóulún", "english": "Cruise ship", "myanmar": "အပျော်စီးသင်္ဘောကြီး"},
    {"chinese": "三轮车", "pinyin": "sānlúnchē", "english": "Tricycle", "myanmar": "သုံးဘီးကား"},
    {"chinese": "人力车", "pinyin": "rénlìchē", "english": "Rickshaw", "myanmar": "ဆိုက်ကား"},
    {"chinese": "共享单车", "pinyin": "gòngxiǎng dānchē", "english": "Shared bike", "myanmar": "အများသုံး စက်ဘီး"},
    {"chinese": "电动自行车", "pinyin": "diàndòng zìxíngchē", "english": "E-bike", "myanmar": "လျှပ်စစ်စက်ဘီး"},
    {"chinese": "滑板车", "pinyin": "huábǎnchē", "english": "Scooter", "myanmar": "စကူတာ"},
    {"chinese": "独轮车", "pinyin": "dúlúnchē", "english": "Unicycle", "myanmar": "ဘီးတစ်ဘီးတည်းစက်ဘီး"},
    {"chinese": "马车", "pinyin": "mǎchē", "english": "Horse carriage", "myanmar": "မြင်းလှည်း"},
    {"chinese": "牛车", "pinyin": "niúchē", "english": "Bullock cart", "myanmar": "နွားလှည်း"},
    {"chinese": "客机", "pinyin": "kèjī", "english": "Passenger plane", "myanmar": "ခရီးသည်တင်လေယာဉ်"},
    {"chinese": "货机", "pinyin": "huòjī", "english": "Cargo plane", "myanmar": "ကုန်တင်လေယာဉ်"},
    {"chinese": "交通工具", "pinyin": "jiāotōng gōngjù", "english": "Means of transport", "myanmar": "သယ်ယူပို့ဆောင်ရေးယာဉ်များ"},
    {"chinese": "交通", "pinyin": "jiāotōng", "english": "Traffic / Transport", "myanmar": "ယာဉ်ကြော / သယ်ယူပို့ဆောင်ရေး"},
    {"chinese": "驾驶", "pinyin": "jiàshǐ", "english": "Drive / Operate", "myanmar": "မောင်းနှင်သည်"},
    {"chinese": "停车", "pinyin": "tíngchē", "english": "Park a vehicle", "myanmar": "ကားရပ်သည်"},
    {"chinese": "开车", "pinyin": "kāichē", "english": "Drive a car", "myanmar": "ကားမောင်းသည်"},
    {"chinese": "乘车", "pinyin": "chéngchē", "english": "Ride / Take a vehicle", "myanmar": "ကားစီးသည်"},
    {"chinese": "人行道", "pinyin": "rénxíngdào", "english": "Sidewalk / Pavement", "myanmar": "လူသွားလမ်း"},
    {"chinese": "立交桥", "pinyin": "lìjiāoqiáo", "english": "Overpass / Flyover", "myanmar": "ခါးကျော်တံတား"},
    {"chinese": "收费站", "pinyin": "shōufèizhàn", "english": "Toll booth", "myanmar": "လမ်းကြေးကောက်ခံစခန်း"},
    ],
  ),
  CategoryItem(
    emoji: "🌧❄",
    titleEn: "Weather / Nature",
    titleMy: "ရာသီဥတု / သဘာဝ",
    words: [
      {"chinese": "天气", "pinyin": "tiānqì", "english": "Weather", "myanmar": "ရာသီဥတု"},
    {"chinese": "太阳", "pinyin": "tàiyáng", "english": "Sun", "myanmar": "နေမင်း / နေ"},
    {"chinese": "月亮", "pinyin": "yuèliang", "english": "Moon", "myanmar": "လမင်း / လ"},
    {"chinese": "星星", "pinyin": "xīngxing", "english": "Star", "myanmar": "ကြယ်"},
    {"chinese": "天空", "pinyin": "tiānkōng", "english": "Sky", "myanmar": "ကောင်းကင်"},
    {"chinese": "云", "pinyin": "yún", "english": "Cloud", "myanmar": "တိမ်"},
    {"chinese": "白云", "pinyin": "báiyún", "english": "White cloud", "myanmar": "တိမ်ဖြူ"},
    {"chinese": "雨", "pinyin": "yǔ", "english": "Rain", "myanmar": "မိုး"},
    {"chinese": "下雨", "pinyin": "xiàyǔ", "english": "To rain", "myanmar": "မိုးရွာသည်"},
    {"chinese": "大雨", "pinyin": "dàyǔ", "english": "Heavy rain", "myanmar": "မိုးကြီး"},
    {"chinese": "小雨", "pinyin": "xiǎoyǔ", "english": "Light rain / Drizzle", "myanmar": "မိုးဖွဲဖွဲ"},
    {"chinese": "雷", "pinyin": "léi", "english": "Thunder", "myanmar": "မိုးကြိုး / မိုးခြိမ်းသံ"},
    {"chinese": "闪电", "pinyin": "shǎndiàn", "english": "Lightning", "myanmar": "လျှပ်စီး"},
    {"chinese": "雷雨", "pinyin": "léiyǔ", "english": "Thunderstorm", "myanmar": "မိုးကြိုးမုန်တိုင်း"},
    {"chinese": "台风", "pinyin": "táifēng", "english": "Typhoon", "myanmar": "တိုင်ဖုန်းမုန်တိုင်း"},
    {"chinese": "暴风雨", "pinyin": "bàofēngyǔ", "english": "Rainstorm / Storm", "myanmar": "မုန်တိုင်း"},
    {"chinese": "雪", "pinyin": "xuě", "english": "Snow", "myanmar": "နှင်း"},
    {"chinese": "下雪", "pinyin": "xiàxuě", "english": "To snow", "myanmar": "နှင်းကျသည်"},
    {"chinese": "冰", "pinyin": "bīng", "english": "Ice", "myanmar": "ရေခဲ"},
    {"chinese": "雾", "pinyin": "wù", "english": "Fog / Mist", "myanmar": "မြူ"},
    {"chinese": "霜", "pinyin": "shuāng", "english": "Frost", "myanmar": "နှင်းခဲ"},
    {"chinese": "风", "pinyin": "fēng", "english": "Wind", "myanmar": "လေ"},
    {"chinese": "大风", "pinyin": "dàfēng", "english": "Strong wind", "myanmar": "လေပြင်း"},
    {"chinese": "微风", "pinyin": "wēifēng", "english": "Breeze", "myanmar": "လေပြေ"},
    {"chinese": "热", "pinyin": "rè", "english": "Hot", "myanmar": "ပူသော"},
    {"chinese": "冷", "pinyin": "lěng", "english": "Cold", "myanmar": "အေးသော"},
    {"chinese": "温暖", "pinyin": "wēnnuǎn", "english": "Warm", "myanmar": "နွေးထွေးသော"},
    {"chinese": "凉快", "pinyin": "liángkuai", "english": "Cool", "myanmar": "အေးမြသော"},
    {"chinese": "晴天", "pinyin": "qíngtiān", "english": "Sunny day", "myanmar": "နေသာသောနေ့"},
    {"chinese": "阴天", "pinyin": "yīntiān", "english": "Overcast day", "myanmar": "တိမ်ဖုံးသောနေ့"},
    {"chinese": "多云", "pinyin": "duōyún", "english": "Cloudy", "myanmar": "တိမ်ထူထပ်သော"},
    {"chinese": "晴朗", "pinyin": "qínglǎng", "english": "Sunny and clear", "myanmar": "သာယာကြည်လင်သော"},
    {"chinese": "潮湿", "pinyin": "cháoshī", "english": "Humid / Damp", "myanmar": "စိုစွတ်သော"},
    {"chinese": "干燥", "pinyin": "gānzào", "english": "Dry", "myanmar": "ခြောက်သွေ့သော"},
    {"chinese": "温度", "pinyin": "wēndù", "english": "Temperature", "myanmar": "အပူချိန်"},
    {"chinese": "气温", "pinyin": "qìwēn", "english": "Air temperature", "myanmar": "လေထုအပူချိန်"},
    {"chinese": "春天", "pinyin": "chūntiān", "english": "Spring", "myanmar": "နွေဦးရာသီ"},
    {"chinese": "夏天", "pinyin": "xiàtiān", "english": "Summer", "myanmar": "နွေရာသီ"},
    {"chinese": "秋天", "pinyin": "qiūtiān", "english": "Autumn / Fall", "myanmar": "ဆောင်းဦးရာသီ"},
    {"chinese": "冬天", "pinyin": "dōngtiān", "english": "Winter", "myanmar": "ဆောင်းရာသီ"},
    {"chinese": "季节", "pinyin": "jìjié", "english": "Season", "myanmar": "ရာသီ"},
    {"chinese": "春风", "pinyin": "chūnfēng", "english": "Spring breeze", "myanmar": "နွေဦးလေပြေ"},
    {"chinese": "阳光", "pinyin": "yángguāng", "english": "Sunlight", "myanmar": "နေရောင်ခြည်"},
    {"chinese": "彩虹", "pinyin": "cǎihóng", "english": "Rainbow", "myanmar": "သက်တံ"},
    {"chinese": "自然", "pinyin": "zìrán", "english": "Nature", "myanmar": "သဘာဝ"},
    {"chinese": "山", "pinyin": "shān", "english": "Mountain", "myanmar": "တောင်"},
    {"chinese": "高山", "pinyin": "gāoshān", "english": "High mountain", "myanmar": "တောင်မြင့်ကြီး"},
    {"chinese": "山谷", "pinyin": "shāngǔ", "english": "Valley", "myanmar": "တောင်ကြား"},
    {"chinese": "河", "pinyin": "hé", "english": "River", "myanmar": "မြစ်"},
    {"chinese": "湖", "pinyin": "hú", "english": "Lake", "myanmar": "အိုင် / ကန်"},
    {"chinese": "海", "pinyin": "hǎi", "english": "Sea", "myanmar": "ပင်လယ်"},
    {"chinese": "海洋", "pinyin": "hǎiyáng", "english": "Ocean", "myanmar": "သမုဒ္ဒရာ"},
    {"chinese": "海滩", "pinyin": "hǎitān", "english": "Beach", "myanmar": "ကမ်းခြေ"},
    {"chinese": "沙滩", "pinyin": "shātān", "english": "Sandy beach", "myanmar": "သဲသောင်ပြင်"},
    {"chinese": "岛", "pinyin": "dǎo", "english": "Island", "myanmar": "ကျွန်း"},
    {"chinese": "森林", "pinyin": "sēnlín", "english": "Forest", "myanmar": "သစ်တော"},
    {"chinese": "树", "pinyin": "shù", "english": "Tree", "myanmar": "သစ်ပင်"},
    {"chinese": "花", "pinyin": "huā", "english": "Flower", "myanmar": "ပန်း"},
    {"chinese": "草", "pinyin": "cǎo", "english": "Grass", "myanmar": "မြက်"},
    {"chinese": "草地", "pinyin": "cǎodì", "english": "Lawn / Grassland", "myanmar": "မြက်ခင်း"},
    {"chinese": "叶子", "pinyin": "yèzi", "english": "Leaf", "myanmar": "အရွက်"},
    {"chinese": "树叶", "pinyin": "shùyè", "english": "Tree leaf", "myanmar": "သစ်ရွက်"},
    {"chinese": "花园", "pinyin": "huāyuán", "english": "Garden", "myanmar": "ပန်းခြံ"},
    {"chinese": "公园", "pinyin": "gōngyuán", "english": "Park", "myanmar": "ဥယျာဉ် / ပန်းခြံ"},
    {"chinese": "土地", "pinyin": "tǔdì", "english": "Land / Soil", "myanmar": "မြေယာ / မြေ"},
    {"chinese": "土壤", "pinyin": "tǔrǎng", "english": "Soil", "myanmar": "မြေဆီလွှာ"},
    {"chinese": "石头", "pinyin": "shítou", "english": "Stone / Rock", "myanmar": "ကျောက်ခဲ"},
    {"chinese": "岩石", "pinyin": "yánshí", "english": "Rock", "myanmar": "ကျောက်ဆောင်"},
    {"chinese": "沙子", "pinyin": "shāzi", "english": "Sand", "myanmar": "သဲ"},
    {"chinese": "泥土", "pinyin": "nítǔ", "english": "Mud / Soil", "myanmar": "ရံ့ / မြေကြီး"},
    {"chinese": "瀑布", "pinyin": "pùbù", "english": "Waterfall", "myanmar": "ရေတံခွန်"},
    {"chinese": "湖水", "pinyin": "húshuǐ", "english": "Lake water", "myanmar": "ကန်ရေ"},
    {"chinese": "河水", "pinyin": "héshuǐ", "english": "River water", "myanmar": "မြစ်ရေ"},
    {"chinese": "海水", "pinyin": "hǎishuǐ", "english": "Seawater", "myanmar": "ပင်လယ်ရေ"},
    {"chinese": "泉水", "pinyin": "quánshuǐ", "english": "Spring water", "myanmar": "စမ်းရေ"},
    {"chinese": "溪流", "pinyin": "xīliú", "english": "Stream / Creek", "myanmar": "စမ်းချောင်း"},
    {"chinese": "丛林", "pinyin": "cónglín", "english": "Jungle", "myanmar": "သစ်တောထူထပ်သောတော"},
    {"chinese": "沙漠", "pinyin": "shāmò", "english": "Desert", "myanmar": "သဲကန္တာရ"},
    {"chinese": "草原", "pinyin": "cǎoyuán", "english": "Grassland / Prairie", "myanmar": "မြက်ခင်းပြင်"},
    {"chinese": "山顶", "pinyin": "shāndǐng", "english": "Mountain peak", "myanmar": "တောင်ထိပ်"},
    {"chinese": "山洞", "pinyin": "shāndòng", "english": "Cave", "myanmar": "တောင်ဂူ"},
    {"chinese": "火山", "pinyin": "huǒshān", "english": "Volcano", "myanmar": "မီးတောင်"},
    {"chinese": "地震", "pinyin": "dìzhèn", "english": "Earthquake", "myanmar": "ငလျင်"},
    {"chinese": "洪水", "pinyin": "hóngshuǐ", "english": "Flood", "myanmar": "ရေကြီးခြင်း"},
    {"chinese": "干旱", "pinyin": "gānhàn", "english": "Drought", "myanmar": "မိုးခေါင်ခြင်း"},
    {"chinese": "风暴", "pinyin": "fēngbào", "english": "Storm", "myanmar": "မုန်တိုင်း"},
    {"chinese": "雷声", "pinyin": "léishēng", "english": "Thunder sound", "myanmar": "မိုးခြိမ်းသံ"},
    {"chinese": "雨滴", "pinyin": "yǔdī", "english": "Raindrop", "myanmar": "မိုးစက်"},
    {"chinese": "雪花", "pinyin": "xuěhuā", "english": "Snowflake", "myanmar": "နှင်းပွင့်"},
    {"chinese": "冰雪", "pinyin": "bīngxuě", "english": "Ice and snow", "myanmar": "ရေခဲနှင့်နှင်း"},
    {"chinese": "空气", "pinyin": "kōngqì", "english": "Air", "myanmar": "လေထု"},
    {"chinese": "环境", "pinyin": "huánjìng", "english": "Environment", "myanmar": "ပတ်ဝန်းကျင်"},
    {"chinese": "地球", "pinyin": "dìqiú", "english": "Earth", "myanmar": "ကမ္ဘာဂြိုဟ်"},
    {"chinese": "世界", "pinyin": "shìjiè", "english": "World", "myanmar": "ကမ္ဘာ"},
    {"chinese": "植物", "pinyin": "zhíwù", "english": "Plant", "myanmar": "အပင်"},
    {"chinese": "动物", "pinyin": "dòngwù", "english": "Animal", "myanmar": "တိရစ္ဆာန်"},
    {"chinese": "天然", "pinyin": "tiānrán", "english": "Natural", "myanmar": "သဘာဝအတိုင်း"},
    {"chinese": "风景", "pinyin": "fēngjǐng", "english": "Scenery / Landscape", "myanmar": "ရှုခင်း"},
    {"chinese": "露水", "pinyin": "lùshuǐ", "english": "Dew", "myanmar": "နှင်းစက်"},
    {"chinese": "晚霞", "pinyin": "wǎnxiá", "english": "Sunset glow", "myanmar": "ဆည်းဆာရောင်"},
    ],
  ),
  CategoryItem(
    emoji: "👚",
    titleEn: "Clothes",
    titleMy: "အဝတ်အစားများ",
    words: [
      {"chinese": "衣服", "pinyin": "yīfu", "english": "Clothes / Clothing", "myanmar": "အဝတ်အစား"},
    {"chinese": "衬衫", "pinyin": "chènshān", "english": "Shirt", "myanmar": "ရှပ်အင်္ကျီ"},
    {"chinese": "T恤", "pinyin": "T-xù", "english": "T-shirt", "myanmar": "တီရှပ်"},
    {"chinese": "裤子", "pinyin": "kùzi", "english": "Pants / Trousers", "myanmar": "ဘောင်းဘီ"},
    {"chinese": "牛仔裤", "pinyin": "niúzǎikù", "english": "Jeans", "myanmar": "ဂျင်းဘောင်းဘီ"},
    {"chinese": "短裤", "pinyin": "duǎnkù", "english": "Shorts", "myanmar": "ဘောင်းဘီတို"},
    {"chinese": "裙子", "pinyin": "qúnzi", "english": "Skirt / Dress", "myanmar": "ဂါဝန် / စကတ်"},
    {"chinese": "连衣裙", "pinyin": "liányīqún", "english": "Dress", "myanmar": "ဂါဝန်"},
    {"chinese": "外套", "pinyin": "wàitào", "english": "Coat / Jacket", "myanmar": "အပြင်အင်္ကျီ / ကုတ်အင်္ကျီ"},
    {"chinese": "大衣", "pinyin": "dàyī", "english": "Overcoat", "myanmar": "ကုတ်အင်္ကျီရှည်"},
    {"chinese": "夹克", "pinyin": "jiákè", "english": "Jacket", "myanmar": "ဂျာကင်အင်္ကျီ"},
    {"chinese": "毛衣", "pinyin": "máoyī", "english": "Sweater", "myanmar": "ဆဝါတာ / သိုးမွေးအင်္ကျီ"},
    {"chinese": "羽绒服", "pinyin": "yǔróngfú", "english": "Down jacket", "myanmar": "အမွှေးထူအင်္ကျီ / ရေခဲရိုက်အင်္ကျီ"},
    {"chinese": "风衣", "pinyin": "fēngyī", "english": "Trench coat / Windbreaker", "myanmar": "လေကာအင်္ကျီ"},
    {"chinese": "西装", "pinyin": "xīzhuāng", "english": "Suit", "myanmar": "ဝတ်စုံပြည့် (ဆုတ်)"},
    {"chinese": "校服", "pinyin": "xiàofú", "english": "School uniform", "myanmar": "ကျောင်းဝတ်စုံ"},
    {"chinese": "制服", "pinyin": "zhìfú", "english": "Uniform", "myanmar": "ယူနီဖောင်း"},
    {"chinese": "睡衣", "pinyin": "shuìyī", "english": "Pajamas", "myanmar": "အိပ်စက်ဝတ်စုံ"},
    {"chinese": "内衣", "pinyin": "nèiyī", "english": "Underwear", "myanmar": "အတွင်းခံအင်္ကျီ"},
    {"chinese": "内裤", "pinyin": "nèikù", "english": "Underpants", "myanmar": "အတွင်းခံဘောင်းဘီ"},
    {"chinese": "袜子", "pinyin": "wàzi", "english": "Socks", "myanmar": "ခြေအိတ်"},
    {"chinese": "鞋子", "pinyin": "xiézi", "english": "Shoes", "myanmar": "ဖိနပ်"},
    {"chinese": "运动鞋", "pinyin": "yùndòngxié", "english": "Sneakers / Sports shoes", "myanmar": "အားကစားဖိနပ်"},
    {"chinese": "皮鞋", "pinyin": "píxié", "english": "Leather shoes", "myanmar": "သားရေဖိနပ်"},
    {"chinese": "凉鞋", "pinyin": "liángxié", "english": "Sandals", "myanmar": "ကြိုးသိုင်းဖိနပ်"},
    {"chinese": "拖鞋", "pinyin": "tuōxié", "english": "Slippers", "myanmar": "ဖိနပ်ပါး / စိပ္ပါး"},
    {"chinese": "靴子", "pinyin": "xuēzi", "english": "Boots", "myanmar": "ဘုက်ဖိနပ်"},
    {"chinese": "高跟鞋", "pinyin": "gāogēnxié", "english": "High heels", "myanmar": "ဒေါက်မြင့်ဖိနပ်"},
    {"chinese": "帽子", "pinyin": "màozi", "english": "Hat / Cap", "myanmar": "ဦးထုပ်"},
    {"chinese": "太阳帽", "pinyin": "tàiyángmào", "english": "Sun hat", "myanmar": "နေကာဦးထုပ်"},
    {"chinese": "围巾", "pinyin": "wéijīn", "english": "Scarf", "myanmar": "မဖလာ / လည်စည်း"},
    {"chinese": "手套", "pinyin": "shǒutào", "english": "Gloves", "myanmar": "လက်အိတ်"},
    {"chinese": "腰带", "pinyin": "yāodài", "english": "Belt", "myanmar": "ခါးပတ်"},
    {"chinese": "领带", "pinyin": "lǐngdài", "english": "Tie / Necktie", "myanmar": "နက်ကတိုင်"},
    {"chinese": "领结", "pinyin": "lǐngjié", "english": "Bowtie", "myanmar": "ဘိုနက်ကတိုင်"},
    {"chinese": "背心", "pinyin": "bèixīn", "english": "Vest / Tank top", "myanmar": "စွပ်ကျယ်အင်္ကျီ / လက်ပြတ်"},
    {"chinese": "马甲", "pinyin": "mǎjiǎ", "english": "Waistcoat / Vest", "myanmar": "ဝတ်စုံလက်ပြတ်အင်္ကျီ"},
    {"chinese": "短袖", "pinyin": "duǎnxiù", "english": "Short sleeves", "myanmar": "လက်တို"},
    {"chinese": "长袖", "pinyin": "chángxiù", "english": "Long sleeves", "myanmar": "လက်ရှည်"},
    {"chinese": "运动服", "pinyin": "yùndòngfú", "english": "Sportswear", "myanmar": "အားကစားဝတ်စုံ"},
    {"chinese": "短裙", "pinyin": "duǎnqún", "english": "Short skirt", "myanmar": "စကတ်တို"},
    {"chinese": "长裙", "pinyin": "chángqún", "english": "Long skirt / dress", "myanmar": "စကတ်ရှည် / ဂါဝန်ရှည်"},
    {"chinese": "半身裙", "pinyin": "bànshēnqún", "english": "Skirt", "myanmar": "စကတ်"},
    {"chinese": "背带裤", "pinyin": "bèidàikù", "english": "Overalls / Dungarees", "myanmar": "ကြိုးသိုင်းဘောင်းဘီ"},
    {"chinese": "休闲裤", "pinyin": "xiūxiánkù", "english": "Casual pants", "myanmar": "ပေါ့ပေါ့ပါးပါးဘောင်းဘီ"},
    {"chinese": "西裤", "pinyin": "xīkù", "english": "Suit trousers", "myanmar": "ကုတ်အင်္ကျီဘောင်းဘီ"},
    {"chinese": "紧身裤", "pinyin": "jǐnshēnkù", "english": "Leggings", "myanmar": "ကပ်ဘောင်းဘီ"},
    {"chinese": "长裤", "pinyin": "chángkù", "english": "Trousers / Long pants", "myanmar": "ဘောင်းဘီရှည်"},
    {"chinese": "雨衣", "pinyin": "yǔyī", "english": "Raincoat", "myanmar": "မိုးကာအင်္ကျီ"},
    {"chinese": "泳衣", "pinyin": "yǒngyī", "english": "Swimsuit", "myanmar": "ရေကူးဝတ်စုံ"},
    {"chinese": "泳裤", "pinyin": "yǒngkù", "english": "Swimming trunks", "myanmar": "ရေကူးဘောင်းဘီ"},
    {"chinese": "睡袍", "pinyin": "shuìpáo", "english": "Nightgown", "myanmar": "အိပ်စက်ဝတ်ရုံ"},
    {"chinese": "浴袍", "pinyin": "yùpáo", "english": "Bathrobe", "myanmar": "ရေချိုးဝတ်ရုံ"},
    {"chinese": "围裙", "pinyin": "wéiqún", "english": "Apron", "myanmar": "ဧပရွန် / ခါးစည်း"},
    {"chinese": "工作服", "pinyin": "gōngzuòfú", "english": "Workwear", "myanmar": "အလုပ်ဝတ်စုံ"},
    {"chinese": "防护服", "pinyin": "fánghùfú", "english": "Protective suit", "myanmar": "ကာကွယ်ရေးဝတ်စုံ"},
    {"chinese": "披风", "pinyin": "pīfēng", "english": "Cape", "myanmar": "ခြုံထည်"},
    {"chinese": "披肩", "pinyin": "pījiān", "english": "Shawl", "myanmar": "ပုခုံးခြုံထည်"},
    {"chinese": "斗篷", "pinyin": "dǒupěng", "english": "Cloak", "myanmar": "ဝတ်ရုံရှည်"},
    {"chinese": "布料", "pinyin": "bùliào", "english": "Fabric / Cloth", "myanmar": "အထည်စ / အထည်သား"},
    {"chinese": "棉衣", "pinyin": "miányī", "english": "Cotton-padded jacket", "myanmar": "ဂွမ်းထိုးအင်္ကျီ"},
    {"chinese": "棉裤", "pinyin": "miánkù", "english": "Cotton-padded trousers", "myanmar": "ဂွမ်းထိုးဘောင်းဘီ"},
    {"chinese": "毛裤", "pinyin": "máokù", "english": "Woolen trousers", "myanmar": "သိုးမွေးဘောင်းဘီ"},
    {"chinese": "皮衣", "pinyin": "píyī", "english": "Leather jacket", "myanmar": "သားရေအင်္ကျီ"},
    {"chinese": "丝绸衣服", "pinyin": "sīchóu yīfu", "english": "Silk clothes", "myanmar": "ပိုးထည်အဝတ်အစား"},
    {"chinese": "花裙子", "pinyin": "huā qúnzi", "english": "Floral dress", "myanmar": "ပန်းရိုက်ဂါဝန်"},
    {"chinese": "白衬衫", "pinyin": "bái chènshān", "english": "White shirt", "myanmar": "ရှပ်အင်္ကျီအဖြူ"},
    {"chinese": "黑裤子", "pinyin": "hēi kùzi", "english": "Black pants", "myanmar": "ဘောင်းဘီအနက်"},
    {"chinese": "红裙子", "pinyin": "hóng qúnzi", "english": "Red dress / skirt", "myanmar": "ဂါဝန်အနီ / စကတ်အနီ"},
    {"chinese": "蓝衣服", "pinyin": "lán yīfu", "english": "Blue clothes", "myanmar": "အပြာရောင်အဝတ်အစား"},
    {"chinese": "绿色外套", "pinyin": "lǜsè wàitào", "english": "Green coat", "myanmar": "အစိမ်းရောင်အပြင်အင်္ကျီ"},
    {"chinese": "黑色鞋子", "pinyin": "hēisè xiézi", "english": "Black shoes", "myanmar": "ဖိနပ်အနက်"},
    {"chinese": "白色袜子", "pinyin": "báisè wàzi", "english": "White socks", "myanmar": "ခြေအိတ်အဖြူ"},
    {"chinese": "眼镜", "pinyin": "yǎnjìng", "english": "Glasses", "myanmar": "မျက်မှန်"},
    {"chinese": "太阳镜", "pinyin": "tàiyángjìng", "english": "Sunglasses", "myanmar": "နေကာမျက်မှန်"},
    {"chinese": "雨鞋", "pinyin": "yǔxié", "english": "Rain boots", "myanmar": "မိုးကာဖိနပ်"},
    {"chinese": "帆布鞋", "pinyin": "fānbùxié", "english": "Canvas shoes", "myanmar": "ကင်းဗတ်ဖိနပ်"},
    {"chinese": "鞋带", "pinyin": "xiédài", "english": "Shoelaces", "myanmar": "ဖိနပ်ကြိုး"},
    {"chinese": "袖子", "pinyin": "xiùzi", "english": "Sleeves", "myanmar": "အင်္ကျီလက်"},
    {"chinese": "口袋", "pinyin": "kǒudài", "english": "Pocket", "myanmar": "အိတ်ကပ်"},
    {"chinese": "拉链", "pinyin": "lāliàn", "english": "Zipper", "myanmar": "ဇစ်"},
    {"chinese": "扣子", "pinyin": "kòuzi", "english": "Button", "myanmar": "ကြယ်သီး"},
    {"chinese": "衣领", "pinyin": "yīlǐng", "english": "Collar", "myanmar": "ကော်လာ"},
    {"chinese": "衣袖", "pinyin": "yīxiù", "english": "Sleeve", "myanmar": "အင်္ကျီလက်စ"},
    {"chinese": "衣柜", "pinyin": "yīguì", "english": "Wardrobe / Closet", "myanmar": "အဝတ်ဘီရို"},
    {"chinese": "衣架", "pinyin": "yījià", "english": "Hanger", "myanmar": "အင်္ကျီချိတ်"},
    {"chinese": "手提包", "pinyin": "shǒutíbāo", "english": "Handbag", "myanmar": "လက်ဆွဲအိတ်"},
    {"chinese": "背包", "pinyin": "bèibāo", "english": "Backpack", "myanmar": "ကျောပိုးအိတ်"},
    {"chinese": "钱包", "pinyin": "qiánbāo", "english": "Wallet / Purse", "myanmar": "ပိုက်ဆံအိတ်"},
    {"chinese": "手表", "pinyin": "shǒubiǎo", "english": "Watch", "myanmar": "လက်ပတ်နာရီ"},
    {"chinese": "手链", "pinyin": "shǒuliàn", "english": "Bracelet", "myanmar": "လက်ကောက် / လက်စွပ်"},
    {"chinese": "项链", "pinyin": "xiàngliàn", "english": "Necklace", "myanmar": "ဆွဲကြိုး"},
    {"chinese": "耳环", "pinyin": "ěrhuán", "english": "Earrings", "myanmar": "နားကပ် / နားဆွဲ"},
    {"chinese": "戒指", "pinyin": "jièzhi", "english": "Ring", "myanmar": "လက်စွပ်"},
    {"chinese": "发夹", "pinyin": "fàjiā", "english": "Hairpin / Hair clip", "myanmar": "ဆံညှပ်"},
    {"chinese": "帽衫", "pinyin": "màoshān", "english": "Hoodie", "myanmar": "ခေါင်းစွပ်အင်္ကျီ"},
    {"chinese": "服装", "pinyin": "fúzhuāng", "english": "Clothing / Apparel", "myanmar": "အဝတ်အထည်"},
    {"chinese": "时装", "pinyin": "shízhuāng", "english": "Fashion", "myanmar": "ခေတ်မီအဝတ်အစား"},
    {"chinese": "传统服装", "pinyin": "chuántǒng fúzhuāng", "english": "Traditional clothing", "myanmar": "ရိုးရာအဝတ်အစား"},
    {"chinese": "胸针", "pinyin": "xiōngzhēn", "english": "Brooch", "myanmar": "ရင်ထိုး"},
    ],
  ),
];