class CategoryItem {
  final String titleEn;
  final String titleMy;
  final List<Map<String, String>> words;
  

  CategoryItem({required this.titleEn, required this.titleMy, required this.words});
}

final List<CategoryItem> appCategories = [
  CategoryItem(
    titleEn: "Animals",
    titleMy: "တိရစ္ဆာန်များ",
    words: [
      {"chinese": "猫", "pinyin": "māo", "english": "Cat", "myanmar": "ကြောင်"},
      {"chinese": "狗", "pinyin": "gǒu", "english": "Dog", "myanmar": "ခွေး"},
      {"chinese": "鸟", "pinyin": "niǎo", "english": "Bird", "myanmar": "ငှက်"},
      {"chinese": "鱼", "pinyin": "yú", "english": "Fish", "myanmar": "ငါး"},
      {"chinese": "马", "pinyin": "mǎ", "english": "Horse", "myanmar": "မြင်း"},
      {"chinese": "牛", "pinyin": "niú", "english": "Cow", "myanmar": "နွား"},
      {"chinese": "羊", "pinyin": "yáng", "english": "Sheep", "myanmar": "သိုး"},
      {"chinese": "猪", "pinyin": "zhū", "english": "Pig", "myanmar": "ဝက်"},
      {"chinese": "鸡", "pinyin": "jī", "english": "Chicken", "myanmar": "ကြက်"},
      {"chinese": "鸭", "pinyin": "yā", "english": "Duck", "myanmar": "ဘဲ"},
      {"chinese": "兔子", "pinyin": "tùzi", "english": "Rabbit", "myanmar": "ယုန်"},
      {"chinese": "老虎", "pinyin": "lǎohǔ", "english": "Tiger", "myanmar": "ကျား"},
      {"chinese": "狮子", "pinyin": "shīzi", "english": "Lion", "myanmar": "ခြင်္သေ့"},
      {"chinese": "大象", "pinyin": "dàxiàng", "english": "Elephant", "myanmar": "ဆင်"},
      {"chinese": "熊猫", "pinyin": "xióngmāo", "english": "Panda", "myanmar": "ပန်ဒါ"},
      {"chinese": "猴子", "pinyin": "hóuzi", "english": "Monkey", "myanmar": "မျောက်"},
      {"chinese": "熊", "pinyin": "xióng", "english": "Bear", "myanmar": "ဝက်ဝံ"},
      {"chinese": "狼", "pinyin": "láng", "english": "Wolf", "myanmar": "ဝံပုလွေ"},
      {"chinese": "蛇", "pinyin": "shé", "english": "Snake", "myanmar": "မြွေ"},
      {"chinese": "青蛙", "pinyin": "qīngwā", "english": "Frog", "myanmar": "ဖား"},
      {"chinese": "乌龟", "pinyin": "wūguī", "english": "Turtle", "myanmar": "လိပ်"},
      {"chinese": "蚂蚁", "pinyin": "mǎyǐ", "english": "Ant", "myanmar": "ပုရွက်ဆိတ်"},
      {"chinese": "蜜蜂", "pinyin": "mìfēng", "english": "Bee", "myanmar": "ပျား"},
      {"chinese": "蝴蝶", "pinyin": "húdié", "english": "Butterfly", "myanmar": "လိပ်ပြာ"},
      {"chinese": "老鼠", "pinyin": "lǎoshǔ", "english": "Mouse", "myanmar": "ကြွက်"},
      {"chinese": "鹿", "pinyin": "lù", "english": "Deer", "myanmar": "သမင်"},
      {"chinese": "长颈鹿", "pinyin": "chángjǐnglù", "english": "Giraffe", "myanmar": "ကုလားအုပ်"},
      {"chinese": "斑马", "pinyin": "bānmǎ", "english": "Zebra", "myanmar": "ကျားသစ်မြင်း"},
      {"chinese": "大熊猫", "pinyin": "dàxióngmāo", "english": "Giant Panda", "myanmar": "ပန်ဒါကြီး"},
      {"chinese": "海豚", "pinyin": "hǎitún", "english": "Dolphin", "myanmar": "လင်းပိုင်"},
    ],
  ),
  CategoryItem(
    titleEn: "Colours",
    titleMy: "အရောင်များ",
    words: [
      {"chinese": "红色", "pinyin": "hóngsè", "english": "Red", "myanmar": "အနီရောင်"},
      {"chinese": "黄色", "pinyin": "huángsè", "english": "Yellow", "myanmar": "အဝါရောင်"},
      {"chinese": "蓝色", "pinyin": "lánsè", "english": "Blue", "myanmar": "အပြာရောင်"},
      {"chinese": "绿色", "pinyin": "lǜsè", "english": "Green", "myanmar": "အစိမ်းရောင်"},
      {"chinese": "黑色", "pinyin": "hēisè", "english": "Black", "myanmar": "အနက်ရောင်"},
      {"chinese": "白色", "pinyin": "báisè", "english": "White", "myanmar": "အဖြူရောင်"},
      {"chinese": "橙色", "pinyin": "chéngsè", "english": "Orange", "myanmar": "လိမ္မော်ရောင်"},
      {"chinese": "紫色", "pinyin": "zǐsè", "english": "Purple", "myanmar": "ခရမ်းရောင်"},
      {"chinese": "粉色", "pinyin": "fěnsè", "english": "Pink", "myanmar": "ပန်းရောင်"},
      {"chinese": "棕色", "pinyin": "zōngsè", "english": "Brown", "myanmar": "အညိုရောင်"},
      {"chinese": "灰色", "pinyin": "huīsè", "english": "Grey", "myanmar": "မီးခိုးရောင်"},
      {"chinese": "金色", "pinyin": "jīnsè", "english": "Gold", "myanmar": "ရွှေရောင်"},
      {"chinese": "银色", "pinyin": "yínsè", "english": "Silver", "myanmar": "ငွေရောင်"},
      {"chinese": "青色", "pinyin": "qīngsè", "english": "Cyan", "myanmar": "အစိမ်းနုရောင်"},
      {"chinese": "米色", "pinyin": "mǐsè", "english": "Beige", "myanmar": "အသားရောင်"},
      {"chinese": "深红色", "pinyin": "shēnhóngsè", "english": "Dark Red", "myanmar": "အနီရင့်"},
      {"chinese": "浅蓝色", "pinyin": "qiǎnlánsè", "english": "Light Blue", "myanmar": "အပြာနု"},
      {"chinese": "深绿色", "pinyin": "shēnlǜsè", "english": "Dark Green", "myanmar": "အစိမ်းရင့်"},
      {"chinese": "浅黄色", "pinyin": "qiǎnhuángsè", "english": "Light Yellow", "myanmar": "အဝါနု"},
      {"chinese": "彩色", "pinyin": "cǎisè", "english": "Colorful", "myanmar": "အရောင်စုံ"},
    ],
  ),
  CategoryItem(
    titleEn: "Numbers",
    titleMy: "ဂဏန်းများ",
    words: [
      {"chinese": "零", "pinyin": "líng", "english": "Zero", "myanmar": "သုည"},
      {"chinese": "一", "pinyin": "yī", "english": "One", "myanmar": "တစ်"},
      {"chinese": "二", "pinyin": "èr", "english": "Two", "myanmar": "နှစ်"},
      {"chinese": "三", "pinyin": "sān", "english": "Three", "myanmar": "သုံး"},
      {"chinese": "四", "pinyin": "sì", "english": "Four", "myanmar": "လေး"},
      {"chinese": "五", "pinyin": "wǔ", "english": "Five", "myanmar": "ငါး"},
      {"chinese": "六", "pinyin": "liù", "english": "Six", "myanmar": "ခြောက်"},
      {"chinese": "七", "pinyin": "qī", "english": "Seven", "myanmar": "ခုနစ်"},
      {"chinese": "八", "pinyin": "bā", "english": "Eight", "myanmar": "ရှစ်"},
      {"chinese": "九", "pinyin": "jiǔ", "english": "Nine", "myanmar": "ကိုး"},
      {"chinese": "十", "pinyin": "shí", "english": "Ten", "myanmar": "ဆယ်"},
      {"chinese": "十一", "pinyin": "shíyī", "english": "Eleven", "myanmar": "တစ်ဆယ့်တစ်"},
      {"chinese": "十二", "pinyin": "shí'èr", "english": "Twelve", "myanmar": "တစ်ဆယ့်နှစ်"},
      {"chinese": "十三", "pinyin": "shísān", "english": "Thirteen", "myanmar": "တစ်ဆယ့်သုံး"},
      {"chinese": "十四", "pinyin": "shísì", "english": "Fourteen", "myanmar": "တစ်ဆယ့်လေး"},
      {"chinese": "十五", "pinyin": "shíwǔ", "english": "Fifteen", "myanmar": "တစ်ဆယ့်ငါး"},
      {"chinese": "十六", "pinyin": "shíliù", "english": "Sixteen", "myanmar": "တစ်ဆယ့်ခြောက်"},
      {"chinese": "十七", "pinyin": "shíqī", "english": "Seventeen", "myanmar": "တစ်ဆယ့်ခုနစ်"},
      {"chinese": "十八", "pinyin": "shíbā", "english": "Eighteen", "myanmar": "တစ်ဆယ့်ရှစ်"},
      {"chinese": "十九", "pinyin": "shíjiǔ", "english": "Nineteen", "myanmar": "တစ်ဆယ့်ကိုး"},
      {"chinese": "二十", "pinyin": "èrshí", "english": "Twenty", "myanmar": "နှစ်ဆယ်"},
      {"chinese": "三十", "pinyin": "sānshí", "english": "Thirty", "myanmar": "သုံးဆယ်"},
      {"chinese": "四十", "pinyin": "sìshí", "english": "Forty", "myanmar": "လေးဆယ်"},
      {"chinese": "五十", "pinyin": "wǔshí", "english": "Fifty", "myanmar": "ငါးဆယ်"},
      {"chinese": "六十", "pinyin": "liùshí", "english": "Sixty", "myanmar": "ခြောက်ဆယ်"},
      {"chinese": "七十", "pinyin": "qīshí", "english": "Seventy", "myanmar": "ခုနစ်ဆယ်"},
      {"chinese": "八十", "pinyin": "bāshí", "english": "Eighty", "myanmar": "ရှစ်ဆယ်"},
      {"chinese": "九十", "pinyin": "jiǔshí", "english": "Ninety", "myanmar": "ကိုးဆယ်"},
      {"chinese": "一百", "pinyin": "yībǎi", "english": "One hundred", "myanmar": "တစ်ရာ"},
      {"chinese": "一千", "pinyin": "yīqiān", "english": "One thousand", "myanmar": "တစ်ထောင်"},
    ],
  ),
  CategoryItem(
    titleEn: "Fruits",
    titleMy: "သစ်သီးဝလံများ",
    words: [
      {"chinese": "苹果", "pinyin": "píngguǒ", "english": "Apple", "myanmar": "ပန်းသီး"},
      {"chinese": "香蕉", "pinyin": "xiāngjiāo", "english": "Banana", "myanmar": "ငှက်ပျောသီး"},
      {"chinese": "橙子", "pinyin": "chéngzi", "english": "Orange", "myanmar": "လိမ္မော်သီး"},
      {"chinese": "橘子", "pinyin": "júzi", "english": "Tangerine", "myanmar": "ကျွဲကောသီး"},
      {"chinese": "葡萄", "pinyin": "pútáo", "english": "Grape", "myanmar": "စပျစ်သီး"},
      {"chinese": "西瓜", "pinyin": "xīguā", "english": "Watermelon", "myanmar": "ဖရဲသီး"},
      {"chinese": "草莓", "pinyin": "cǎoméi", "english": "Strawberry", "myanmar": "စတော်ဘယ်ရီ"},
      {"chinese": "芒果", "pinyin": "mángguǒ", "english": "Mango", "myanmar": "သရက်သီး"},
      {"chinese": "菠萝", "pinyin": "bōluó", "english": "Pineapple", "myanmar": "နာနတ်သီး"},
      {"chinese": "柠檬", "pinyin": "níngméng", "english": "Lemon", "myanmar": "သံပရာသီး"},
      {"chinese": "梨", "pinyin": "lí", "english": "Pear", "myanmar": "သစ်တော်သီး"},
      {"chinese": "桃子", "pinyin": "táozi", "english": "Peach", "myanmar": "မက်မွန်သီး"},
      {"chinese": "李子", "pinyin": "lǐzi", "english": "Plum", "myanmar": "ဇီးသီး"},
      {"chinese": "樱桃", "pinyin": "yīngtáo", "english": "Cherry", "myanmar": "ချယ်ရီသီး"},
      {"chinese": "石榴", "pinyin": "shíliú", "english": "Pomegranate", "myanmar": "သလဲသီး"},
      {"chinese": "猕猴桃", "pinyin": "míhóutáo", "english": "Kiwi", "myanmar": "ကီဝီသီး"},
      {"chinese": "火龙果", "pinyin": "huǒlóngguǒ", "english": "Dragon fruit", "myanmar": "နဂါးမောက်သီး"},
      {"chinese": "木瓜", "pinyin": "mùguā", "english": "Papaya", "myanmar": "သင်္ဘောသီး"},
      {"chinese": "椰子", "pinyin": "yēzi", "english": "Coconut", "myanmar": "အုန်းသီး"},
      {"chinese": "柚子", "pinyin": "yòuzi", "english": "Pomelo", "myanmar": "ကျွဲကောသီး"},
      {"chinese": "柿子", "pinyin": "shìzi", "english": "Persimmon", "myanmar": "သစ်တော်သီးအမျိုးအစား"},
      {"chinese": "蓝莓", "pinyin": "lánméi", "english": "Blueberry", "myanmar": "ဘလူးဘယ်ရီ"},
      {"chinese": "覆盆子", "pinyin": "fùpénzi", "english": "Raspberry", "myanmar": "ရာ့စ်ဘယ်ရီ"},
      {"chinese": "哈密瓜", "pinyin": "hāmìguā", "english": "Cantaloupe", "myanmar": "ဖရဲသီးအမျိုးအစား"},
      {"chinese": "榴莲", "pinyin": "liúlián", "english": "Durian", "myanmar": "ဒူးရင်းသီး"},
      {"chinese": "牛油果", "pinyin": "niúyóuguǒ", "english": "Avocado", "myanmar": "ထောပတ်သီး"},
      {"chinese": "无花果", "pinyin": "wúhuāguǒ", "english": "Fig", "myanmar": "သဖန်းသီး"},
      {"chinese": "山竹", "pinyin": "shānzhú", "english": "Mangosteen", "myanmar": "မင်းကွတ်သီး"},
      {"chinese": "荔枝", "pinyin": "lìzhī", "english": "Lychee", "myanmar": "လိုင်ချီးသီး"},
      {"chinese": "龙眼", "pinyin": "lóngyǎn", "english": "Longan", "myanmar": "လန်းယန်သီး"},
    ],
  ),
  CategoryItem(
    titleEn: "Food",
    titleMy: "အစားအစာများ",
    words: [
      {"chinese": "米饭", "pinyin": "mǐfàn", "english": "Rice", "myanmar": "ထမင်း"},
      {"chinese": "面条", "pinyin": "miàntiáo", "english": "Noodles", "myanmar": "ခေါက်ဆွဲ"},
      {"chinese": "面包", "pinyin": "miànbāo", "english": "Bread", "myanmar": "ပေါင်မုန့်"},
      {"chinese": "饺子", "pinyin": "jiǎozi", "english": "Dumplings", "myanmar": "ဂျောက်ဆီ"},
      {"chinese": "包子", "pinyin": "bāozi", "english": "Steamed bun", "myanmar": "ပေါင်းမုန့်"},
      {"chinese": "馒头", "pinyin": "mántou", "english": "Steamed bun", "myanmar": "ပေါင်းမုန့်အမျိုးအစား"},
      {"chinese": "粥", "pinyin": "zhōu", "english": "Porridge", "myanmar": "ဆန်ပြုတ်"},
      {"chinese": "鸡蛋", "pinyin": "jīdàn", "english": "Egg", "myanmar": "ကြက်ဥ"},
      {"chinese": "鸡肉", "pinyin": "jīròu", "english": "Chicken", "myanmar": "ကြက်သား"},
      {"chinese": "牛肉", "pinyin": "niúròu", "english": "Beef", "myanmar": "အမဲသား"},
      {"chinese": "猪肉", "pinyin": "zhūròu", "english": "Pork", "myanmar": "ဝက်သား"},
      {"chinese": "鱼", "pinyin": "yú", "english": "Fish", "myanmar": "ငါး"},
      {"chinese": "虾", "pinyin": "xiā", "english": "Shrimp", "myanmar": "ပုစွန်"},
      {"chinese": "蔬菜", "pinyin": "shūcài", "english": "Vegetable", "myanmar": "ဟင်းသီးဟင်းရွက်"},
      {"chinese": "水果", "pinyin": "shuǐguǒ", "english": "Fruit", "myanmar": "သစ်သီး"},
      {"chinese": "土豆", "pinyin": "tǔdòu", "english": "Potato", "myanmar": "အာလူး"},
      {"chinese": "西红柿", "pinyin": "xīhóngshì", "english": "Tomato", "myanmar": "ခရမ်းချဉ်သီး"},
      {"chinese": "胡萝卜", "pinyin": "húluóbo", "english": "Carrot", "myanmar": "မုန်လာဥနီ"},
      {"chinese": "白菜", "pinyin": "báicài", "english": "Cabbage", "myanmar": "ဂေါ်ဖီထုပ်"},
      {"chinese": "玉米", "pinyin": "yùmǐ", "english": "Corn", "myanmar": "ပြောင်းဖူး"},
      {"chinese": "豆腐", "pinyin": "dòufu", "english": "Tofu", "myanmar": "တို့ဟူး"},
      {"chinese": "汤", "pinyin": "tāng", "english": "Soup", "myanmar": "ဟင်းချို"},
      {"chinese": "沙拉", "pinyin": "shālā", "english": "Salad", "myanmar": "သုပ်"},
      {"chinese": "披萨", "pinyin": "pīsà", "english": "Pizza", "myanmar": "ပီဇာ"},
      {"chinese": "汉堡", "pinyin": "hànbǎo", "english": "Hamburger", "myanmar": "ဟမ်ဘာဂါ"},
      {"chinese": "三明治", "pinyin": "sānmíngzhì", "english": "Sandwich", "myanmar": "ဆန်းဒဝစ်"},
      {"chinese": "蛋糕", "pinyin": "dàngāo", "english": "Cake", "myanmar": "ကိတ်မုန့်"},
      {"chinese": "饼干", "pinyin": "bǐnggān", "english": "Cookie", "myanmar": "ဘီစကစ်"},
      {"chinese": "冰淇淋", "pinyin": "bīngqílín", "english": "Ice cream", "myanmar": "ရေခဲမုန့်"},
      {"chinese": "巧克力", "pinyin": "qiǎokèlì", "english": "Chocolate", "myanmar": "ချောကလက်"},
      {"chinese": "糖", "pinyin": "táng", "english": "Sugar", "myanmar": "သကြား"},
      {"chinese": "盐", "pinyin": "yán", "english": "Salt", "myanmar": "ဆား"},
      {"chinese": "米粉", "pinyin": "mǐfěn", "english": "Rice noodles", "myanmar": "ဆန်ခေါက်ဆွဲ"},
      {"chinese": "炒饭", "pinyin": "chǎofàn", "english": "Fried rice", "myanmar": "ထမင်းကြော်"},
      {"chinese": "火锅", "pinyin": "huǒguō", "english": "Hot pot", "myanmar": "ဟော့ပေါ့"},
      {"chinese": "春卷", "pinyin": "chūnjuǎn", "english": "Spring rolls", "myanmar": "သင်္ဘောသီးကြော်"},
      {"chinese": "烤肉", "pinyin": "kǎoròu", "english": "Barbecue", "myanmar": "အကင်"},
      {"chinese": "香肠", "pinyin": "xiāngcháng", "english": "Sausage", "myanmar": "ဝက်အူချောင်း"},
      {"chinese": "奶酪", "pinyin": "nǎilào", "english": "Cheese", "myanmar": "ဒိန်ခဲ"},
      {"chinese": "蜂蜜", "pinyin": "fēngmì", "english": "Honey", "myanmar": "ပျားရည်"},
    ],
  ),
  CategoryItem(
    titleEn: "Family / People",
    titleMy: "မိသားစု / လူများ",
    words: [
      {"chinese": "爸爸", "pinyin": "bàba", "english": "Father", "myanmar": "ဖခင်"},
      {"chinese": "妈妈", "pinyin": "māma", "english": "Mother", "myanmar": "မိခင်"},
      {"chinese": "父亲", "pinyin": "fùqīn", "english": "Father", "myanmar": "ဖခင်"},
      {"chinese": "母亲", "pinyin": "mǔqīn", "english": "Mother", "myanmar": "မိခင်"},
      {"chinese": "哥哥", "pinyin": "gēge", "english": "Older brother", "myanmar": "အစ်ကို"},
      {"chinese": "姐姐", "pinyin": "jiějie", "english": "Older sister", "myanmar": "အစ်မ"},
      {"chinese": "弟弟", "pinyin": "dìdi", "english": "Younger brother", "myanmar": "ညီ"},
      {"chinese": "妹妹", "pinyin": "mèimei", "english": "Younger sister", "myanmar": "ညီမ"},
      {"chinese": "爷爷", "pinyin": "yéye", "english": "Grandfather", "myanmar": "အဘိုး"},
      {"chinese": "奶奶", "pinyin": "nǎinai", "english": "Grandmother", "myanmar": "အဘွား"},
      {"chinese": "外公", "pinyin": "wàigōng", "english": "Grandfather", "myanmar": "အဘိုး"},
      {"chinese": "外婆", "pinyin": "wàipó", "english": "Grandmother", "myanmar": "အဘွား"},
      {"chinese": "丈夫", "pinyin": "zhàngfū", "english": "Husband", "myanmar": "ခင်ပွန်း"},
      {"chinese": "妻子", "pinyin": "qīzi", "english": "Wife", "myanmar": "ဇနီး"},
      {"chinese": "儿子", "pinyin": "érzi", "english": "Son", "myanmar": "သား"},
      {"chinese": "女儿", "pinyin": "nǚ'ér", "english": "Daughter", "myanmar": "သမီး"},
      {"chinese": "孩子", "pinyin": "háizi", "english": "Child", "myanmar": "ကလေး"},
      {"chinese": "家人", "pinyin": "jiārén", "english": "Family member", "myanmar": "မိသားစုဝင်"},
      {"chinese": "朋友", "pinyin": "péngyǒu", "english": "Friend", "myanmar": "သူငယ်ချင်း"},
      {"chinese": "同学", "pinyin": "tóngxué", "english": "Classmate", "myanmar": "အတန်းဖော်"},
      {"chinese": "老师", "pinyin": "lǎoshī", "english": "Teacher", "myanmar": "ဆရာ"},
      {"chinese": "学生", "pinyin": "xuésheng", "english": "Student", "myanmar": "ကျောင်းသား"},
      {"chinese": "医生", "pinyin": "yīshēng", "english": "Doctor", "myanmar": "ဆရာဝန်"},
      {"chinese": "护士", "pinyin": "hùshi", "english": "Nurse", "myanmar": "သူနာပြု"},
      {"chinese": "警察", "pinyin": "jǐngchá", "english": "Police", "myanmar": "ရဲ"},
      {"chinese": "司机", "pinyin": "sījī", "english": "Driver", "myanmar": "ယာဉ်မောင်း"},
      {"chinese": "老人", "pinyin": "lǎorén", "english": "Old person", "myanmar": "သက်ကြီးရွယ်အို"},
      {"chinese": "男孩", "pinyin": "nánhái", "english": "Boy", "myanmar": "ယောက်ျားလေး"},
      {"chinese": "女孩", "pinyin": "nǚhái", "english": "Girl", "myanmar": "မိန်းကလေး"},
      {"chinese": "男人", "pinyin": "nánrén", "english": "Man", "myanmar": "ယောက်ျား"},
      {"chinese": "女人", "pinyin": "nǚrén", "english": "Woman", "myanmar": "မိန်းမ"},
      {"chinese": "人", "pinyin": "rén", "english": "Person", "myanmar": "လူ"},
    ],
  ),
  CategoryItem(
    titleEn: "School",
    titleMy: "ကျောင်း",
    words: [
      {"chinese": "学校", "pinyin": "xuéxiào", "english": "School", "myanmar": "ကျောင်း"},
      {"chinese": "学生", "pinyin": "xuésheng", "english": "Student", "myanmar": "ကျောင်းသား"},
      {"chinese": "老师", "pinyin": "lǎoshī", "english": "Teacher", "myanmar": "ဆရာ"},
      {"chinese": "教室", "pinyin": "jiàoshì", "english": "Classroom", "myanmar": "စာသင်ခန်း"},
      {"chinese": "课本", "pinyin": "kèběn", "english": "Textbook", "myanmar": "စာအုပ်"},
      {"chinese": "书", "pinyin": "shū", "english": "Book", "myanmar": "စာအုပ်"},
      {"chinese": "笔", "pinyin": "bǐ", "english": "Pen", "myanmar": "ဘောပင်"},
      {"chinese": "铅笔", "pinyin": "qiānbǐ", "english": "Pencil", "myanmar": "ခဲတံ"},
      {"chinese": "橡皮", "pinyin": "xiàngpí", "english": "Eraser", "myanmar": "ခဲဖျက်"},
      {"chinese": "尺子", "pinyin": "chǐzi", "english": "Ruler", "myanmar": "ပေတံ"},
      {"chinese": "书包", "pinyin": "shūbāo", "english": "School bag", "myanmar": "ကျောင်းလွယ်အိတ်"},
      {"chinese": "桌子", "pinyin": "zhuōzi", "english": "Table", "myanmar": "စားပွဲ"},
      {"chinese": "椅子", "pinyin": "yǐzi", "english": "Chair", "myanmar": "ကုလားထိုင်"},
      {"chinese": "黑板", "pinyin": "hēibǎn", "english": "Blackboard", "myanmar": "ကျောက်သင်ပုန်း"},
      {"chinese": "白板", "pinyin": "báibǎn", "english": "Whiteboard", "myanmar": "ဘုတ်ဖြူ"},
      {"chinese": "作业", "pinyin": "zuòyè", "english": "Homework", "myanmar": "အိမ်စာ"},
      {"chinese": "考试", "pinyin": "kǎoshì", "english": "Exam", "myanmar": "စာမေးပွဲ"},
      {"chinese": "课程", "pinyin": "kèchéng", "english": "Course", "myanmar": "သင်ခန်းစာ"},
      {"chinese": "汉语", "pinyin": "hànyǔ", "english": "Chinese", "myanmar": "တရုတ်ဘာသာ"},
      {"chinese": "数学", "pinyin": "shùxué", "english": "Math", "myanmar": "သင်္ချာ"},
      {"chinese": "英语", "pinyin": "yīngyǔ", "english": "English", "myanmar": "အင်္ဂလိပ်ဘာသာ"},
      {"chinese": "科学", "pinyin": "kēxué", "english": "Science", "myanmar": "သိပ္ပံ"},
      {"chinese": "历史", "pinyin": "lìshǐ", "english": "History", "myanmar": "သမိုင်း"},
      {"chinese": "地理", "pinyin": "dìlǐ", "english": "Geography", "myanmar": "ပထဝီ"},
      {"chinese": "图书馆", "pinyin": "túshūguǎn", "english": "Library", "myanmar": "စာကြည့်တိုက်"},
      {"chinese": "校长", "pinyin": "xiàozhǎng", "english": "Principal", "myanmar": "ကျောင်းအုပ်"},
      {"chinese": "同学", "pinyin": "tóngxué", "english": "Classmate", "myanmar": "အတန်းဖော်"},
      {"chinese": "大学", "pinyin": "dàxué", "english": "University", "myanmar": "တက္ကသိုလ်"},
      {"chinese": "中学", "pinyin": "zhōngxué", "english": "Middle school", "myanmar": "အလယ်တန်းကျောင်း"},
      {"chinese": "小学", "pinyin": "xiǎoxué", "english": "Elementary school", "myanmar": "မူလတန်းကျောင်း"},
    ],
  ),
  CategoryItem(
    titleEn: "Transport",
    titleMy: "သယ်ယူပို့ဆောင်ရေး",
    words: [
      {"chinese": "汽车", "pinyin": "qìchē", "english": "Car", "myanmar": "ကား"},
      {"chinese": "公共汽车", "pinyin": "gōnggòng qìchē", "english": "Bus", "myanmar": "ဘတ်စ်ကား"},
      {"chinese": "火车", "pinyin": "huǒchē", "english": "Train", "myanmar": "ရထား"},
      {"chinese": "地铁", "pinyin": "dìtiě", "english": "Subway", "myanmar": "မြေအောက်ရထား"},
      {"chinese": "飞机", "pinyin": "fēijī", "english": "Airplane", "myanmar": "လေယာဉ်"},
      {"chinese": "船", "pinyin": "chuán", "english": "Boat", "myanmar": "လှေ"},
      {"chinese": "自行车", "pinyin": "zìxíngchē", "english": "Bicycle", "myanmar": "စက်ဘီး"},
      {"chinese": "摩托车", "pinyin": "mótuōchē", "english": "Motorcycle", "myanmar": "ဆိုင်ကယ်"},
      {"chinese": "出租车", "pinyin": "chūzūchē", "english": "Taxi", "myanmar": "တက္ကစီ"},
      {"chinese": "卡车", "pinyin": "kǎchē", "english": "Truck", "myanmar": "ကုန်တင်ကား"},
      {"chinese": "救护车", "pinyin": "jiùhùchē", "english": "Ambulance", "myanmar": "လူနာတင်ကား"},
      {"chinese": "警车", "pinyin": "jǐngchē", "english": "Police car", "myanmar": "ရဲကား"},
      {"chinese": "消防车", "pinyin": "xiāofángchē", "english": "Fire truck", "myanmar": "မီးသတ်ကား"},
      {"chinese": "电动车", "pinyin": "diàndòngchē", "english": "Electric vehicle", "myanmar": "လျှပ်စစ်ကား"},
      {"chinese": "高铁", "pinyin": "gāotiě", "english": "High-speed rail", "myanmar": "အမြန်ရထား"},
      {"chinese": "火车站", "pinyin": "huǒchēzhàn", "english": "Train station", "myanmar": "ဘူတာရုံ"},
      {"chinese": "机场", "pinyin": "jīchǎng", "english": "Airport", "myanmar": "လေဆိပ်"},
      {"chinese": "地铁站", "pinyin": "dìtiězhàn", "english": "Subway station", "myanmar": "မြေအောက်ရထားဘူတာ"},
      {"chinese": "公共汽车站", "pinyin": "gōnggòng qìchēzhàn", "english": "Bus station", "myanmar": "ကားမှတ်တိုင်"},
      {"chinese": "轮船", "pinyin": "lúnchuán", "english": "Ship", "myanmar": "သင်္ဘော"},
      {"chinese": "直升机", "pinyin": "zhíshēngjī", "english": "Helicopter", "myanmar": "ရဟတ်ယာဉ်"},
      {"chinese": "电车", "pinyin": "diànchē", "english": "Tram", "myanmar": "လျှပ်စစ်ရထား"},
      {"chinese": "车站", "pinyin": "chēzhàn", "english": "Station", "myanmar": "ဘူတာ"},
      {"chinese": "马路", "pinyin": "mǎlù", "english": "Road", "myanmar": "လမ်း"},
      {"chinese": "红绿灯", "pinyin": "hónglǜdēng", "english": "Traffic light", "myanmar": "မီးပွိုင့်"},
    ],
  ),
  CategoryItem(
    titleEn: "Weather / Nature",
    titleMy: "ရာသီဥတု / သဘာဝ",
    words: [
      {"chinese": "天气", "pinyin": "tiānqì", "english": "Weather", "myanmar": "ရာသီဥတု"},
      {"chinese": "晴天", "pinyin": "qíngtiān", "english": "Sunny", "myanmar": "သာယာသောနေ့"},
      {"chinese": "阴天", "pinyin": "yīntiān", "english": "Cloudy", "myanmar": "တိမ်ထူသောနေ့"},
      {"chinese": "下雨", "pinyin": "xiàyǔ", "english": "Rain", "myanmar": "မိုးရွာ"},
      {"chinese": "下雪", "pinyin": "xiàxuě", "english": "Snow", "myanmar": "နှင်းကျ"},
      {"chinese": "雨", "pinyin": "yǔ", "english": "Rain", "myanmar": "မိုး"},
      {"chinese": "雪", "pinyin": "xuě", "english": "Snow", "myanmar": "နှင်း"},
      {"chinese": "风", "pinyin": "fēng", "english": "Wind", "myanmar": "လေ"},
      {"chinese": "云", "pinyin": "yún", "english": "Cloud", "myanmar": "တိမ်"},
      {"chinese": "太阳", "pinyin": "tàiyáng", "english": "Sun", "myanmar": "နေ"},
      {"chinese": "月亮", "pinyin": "yuèliàng", "english": "Moon", "myanmar": "လ"},
      {"chinese": "星星", "pinyin": "xīngxīng", "english": "Star", "myanmar": "ကြယ်"},
      {"chinese": "雷", "pinyin": "léi", "english": "Thunder", "myanmar": "မိုးကြိုး"},
      {"chinese": "闪电", "pinyin": "shǎndiàn", "english": "Lightning", "myanmar": "လျှပ်စီး"},
      {"chinese": "彩虹", "pinyin": "cǎihóng", "english": "Rainbow", "myanmar": "သက်တံ့"},
      {"chinese": "雾", "pinyin": "wù", "english": "Fog", "myanmar": "မြူ"},
      {"chinese": "热", "pinyin": "rè", "english": "Hot", "myanmar": "ပူ"},
      {"chinese": "冷", "pinyin": "lěng", "english": "Cold", "myanmar": "အေး"},
      {"chinese": "春天", "pinyin": "chūntiān", "english": "Spring", "myanmar": "နွေဦး"},
      {"chinese": "夏天", "pinyin": "xiàtiān", "english": "Summer", "myanmar": "နွေရာသီ"},
      {"chinese": "秋天", "pinyin": "qiūtiān", "english": "Autumn", "myanmar": "ဆောင်းဦး"},
      {"chinese": "冬天", "pinyin": "dōngtiān", "english": "Winter", "myanmar": "ဆောင်းရာသီ"},
      {"chinese": "山", "pinyin": "shān", "english": "Mountain", "myanmar": "တောင်"},
      {"chinese": "河", "pinyin": "hé", "english": "River", "myanmar": "မြစ်"},
      {"chinese": "湖", "pinyin": "hú", "english": "Lake", "myanmar": "အိုင်"},
      {"chinese": "海", "pinyin": "hǎi", "english": "Sea", "myanmar": "ပင်လယ်"},
      {"chinese": "海滩", "pinyin": "hǎitān", "english": "Beach", "myanmar": "ကမ်းခြေ"},
      {"chinese": "树", "pinyin": "shù", "english": "Tree", "myanmar": "သစ်ပင်"},
      {"chinese": "花", "pinyin": "huā", "english": "Flower", "myanmar": "ပန်း"},
      {"chinese": "草", "pinyin": "cǎo", "english": "Grass", "myanmar": "မြက်"},
      {"chinese": "森林", "pinyin": "sēnlín", "english": "Forest", "myanmar": "တော"},
      {"chinese": "石头", "pinyin": "shítou", "english": "Stone", "myanmar": "ကျောက်တုံး"},
      {"chinese": "天空", "pinyin": "tiānkōng", "english": "Sky", "myanmar": "ကောင်းကင်"},
      {"chinese": "地球", "pinyin": "dìqiú", "english": "Earth", "myanmar": "ကမ္ဘာမြေ"},
      {"chinese": "火", "pinyin": "huǒ", "english": "Fire", "myanmar": "မီး"},
    ],
  ),
  CategoryItem(
    titleEn: "Clothes",
    titleMy: "အဝတ်အစားများ",
    words: [
      {"chinese": "衣服", "pinyin": "yīfu", "english": "Clothes", "myanmar": "အဝတ်အစား"},
      {"chinese": "裤子", "pinyin": "kùzi", "english": "Pants", "myanmar": "ဘောင်းဘီ"},
      {"chinese": "裙子", "pinyin": "qúnzi", "english": "Skirt", "myanmar": "စကတ်"},
      {"chinese": "衬衫", "pinyin": "chènshān", "english": "Shirt", "myanmar": "ရှပ်အင်္ကျီ"},
      {"chinese": "T恤", "pinyin": "T-xù", "english": "T-shirt", "myanmar": "တီရှပ်"},
      {"chinese": "外套", "pinyin": "wàitào", "english": "Coat", "myanmar": "ဂျာကင်အင်္ကျီ"},
      {"chinese": "毛衣", "pinyin": "máoyī", "english": "Sweater", "myanmar": "ဆွယ်တာ"},
      {"chinese": "大衣", "pinyin": "dàyī", "english": "Overcoat", "myanmar": "ကုတ်အင်္ကျီ"},
      {"chinese": "短裤", "pinyin": "duǎnkù", "english": "Shorts", "myanmar": "ဘောင်းဘီတို"},
      {"chinese": "牛仔裤", "pinyin": "niúzǎikù", "english": "Jeans", "myanmar": "ဂျင်းဘောင်းဘီ"},
      {"chinese": "鞋子", "pinyin": "xiézi", "english": "Shoes", "myanmar": "ဖိနပ်"},
      {"chinese": "袜子", "pinyin": "wàzi", "english": "Socks", "myanmar": "ခြေအိတ်"},
      {"chinese": "帽子", "pinyin": "màozi", "english": "Hat", "myanmar": "ဦးထုပ်"},
      {"chinese": "围巾", "pinyin": "wéijīn", "english": "Scarf", "myanmar": "ပဝါ"},
      {"chinese": "手套", "pinyin": "shǒutào", "english": "Gloves", "myanmar": "လက်အိတ်"},
      {"chinese": "皮带", "pinyin": "pídài", "english": "Belt", "myanmar": "ခါးပတ်"},
      {"chinese": "睡衣", "pinyin": "shuìyī", "english": "Pajamas", "myanmar": "ညအိပ်ဝတ်စုံ"},
      {"chinese": "内衣", "pinyin": "nèiyī", "english": "Underwear", "myanmar": "အတွင်းခံ"},
      {"chinese": "雨衣", "pinyin": "yǔyī", "english": "Raincoat", "myanmar": "မိုးကာအင်္ကျီ"},
      {"chinese": "运动鞋", "pinyin": "yùndòngxié", "english": "Sneakers", "myanmar": "အားကစားဖိနပ်"},
      {"chinese": "凉鞋", "pinyin": "liángxié", "english": "Sandals", "myanmar": "ဖိနပ်"},
      {"chinese": "靴子", "pinyin": "xuēzi", "english": "Boots", "myanmar": "ဖိနပ်ရှည်"},
      {"chinese": "眼镜", "pinyin": "yǎnjìng", "english": "Glasses", "myanmar": "မျက်မှန်"},
      {"chinese": "手表", "pinyin": "shǒubiǎo", "english": "Watch", "myanmar": "နာရီလက်ပတ်"},
      {"chinese": "背包", "pinyin": "bēibāo", "english": "Backpack", "myanmar": "ကျောပိုးအိတ်"},
    ],
  ),
];